<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan">
  <title>Econometrics I – Introduction to Econometrics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-70fcdf68ba588c6f83f9e4af10fa12ef.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- shared interactive layer for all Econometrics I decks -->
  <script src="assets/wooldridge-data.js"></script>
  <script src="assets/hmda-data.js"></script>
  <script src="assets/econ-core.js"></script>
  <script src="assets/econ-ui.js"></script>
  <script src="assets/widgets-shared.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introduction to Econometrics</h1>
  <p class="subtitle">Topic 1 · What is econometrics? Data, causality and <em>ceteris paribus</em></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan 
</div>
        <p class="quarto-title-affiliation">
            Yıldız Technical University · Department of Economics
          </p>
    </div>
</div>

  <p class="date">Fall 2026</p>
</section>
<section id="todays-roadmap" class="slide level2">
<h2>Today’s roadmap</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="objectives">
<p><strong>By the end of this lecture you should be able to</strong></p>
<ul>
<li>explain what econometrics is and why it needs its <strong>own</strong> methods</li>
<li>describe the steps of an <strong>empirical economic analysis</strong></li>
<li>turn an <strong>economic model</strong> into an <strong>econometric model</strong></li>
<li>recognize the four <strong>types of economic data</strong></li>
<li>explain <strong>causality</strong>, <strong><em>ceteris paribus</em></strong> and why <em>correlation ≠ causation</em></li>
<li>explain why <strong>randomized experiments</strong> are the benchmark</li>
</ul>
</div>
</div><div class="column" style="width:45%;">
<div class="card">
<p><span class="ct">Reading</span></p>
<p><span class="tag weektag">Fall 2026 · Week 1</span></p>
<p><span class="tag">Wooldridge ch.&nbsp;1</span> <span class="tag">Heiss ch.&nbsp;1</span> <span class="tag">Stock &amp; Watson ch.&nbsp;1–3</span></p>
</div>
<div class="card">
<p><span class="ct">Lab this week</span></p>
<p>Complete the free DataCamp course <strong>Introduction to R</strong> before next week’s lab.</p>
</div>
<div class="card">
<p><span class="ct">How to use these slides</span></p>
<p><strong>F</strong> full screen · <strong>Esc</strong> overview · <strong>M</strong> menu. Blue boxes are ungraded <strong>self-checks</strong>.</p>
</div>
</div></div>
<aside class="notes">
<p>Hands-on slides: the interactive parts run in any browser, and no installation is needed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warm-up-why-do-graduates-earn-more" class="slide level2">
<h2>Warm-up: why do graduates earn more?</h2>
<p>Average hourly wage by years of schooling, 526 U.S. workers (<code>wage1</code>): <span style="font-weight:700; color:#1f5fa8">$5.37</span> at <strong>12 years</strong> (high school) and <span style="font-weight:700; color:#d9622b">$8.04</span> at <strong>16 years</strong> (college).</p>
<div class="quiz" data-id="w1-warmup" data-answer="a,b,c">
<p><strong>College graduates earn about 50% more. Which explanations could account for this gap? Select all that apply.</strong></p>
<p><span data-opt="a">A) College makes people more productive</span></p>
<p><span data-opt="b">B) More able or more motivated people are more likely to go to college</span></p>
<p><span data-opt="c">C) Richer families help their children with both schooling <em>and</em> finding good jobs</span></p>
<p><span data-opt="d">D) None of these: the gap must be caused by education alone</span></p>
<div class="explain">
<p>All of A, B and C could be at work. The gap mixes the <strong>causal effect of education</strong> (A) with <strong>ability</strong> (B) and <strong>family background</strong> (C). Measuring the effect of education <strong>holding other factors fixed</strong> is the central problem of econometrics.</p>
</div>
</div>
</section>
<section>
<section id="what-is-econometrics" class="title-slide slide level1 section-slide center">
<h1>What is econometrics?</h1>
<p>What the field is, what it is made of, and how it differs from statistics and machine learning.</p>
</section>
<section id="definitions" class="slide level2">
<h2>Definitions</h2>
<blockquote>
<p>“Econometrics may be defined as the social science in which the tools of <strong>economic theory, mathematics, and statistical inference</strong> are applied to the analysis of economic phenomena.”</p>
<p>— Arthur S. Goldberger (1964)</p>
</blockquote>
<div class="fragment">
<blockquote>
<p>“…the quantitative analysis of actual economic phenomena based on the concurrent development of <strong>theory and observation</strong>, related by appropriate methods of inference.”</p>
<p>— Paul A. Samuelson et al.</p>
</blockquote>
</div>
<div class="fragment">
<p><strong>Literally</strong> “economic measurement”, but the field is wider: <strong>estimating</strong> economic relationships, <strong>testing</strong> theories, <strong>evaluating</strong> policies and <strong>forecasting</strong>.</p>
</div>
</section>
<section id="why-a-separate-discipline" class="slide level2 smaller">
<h2>Why a separate discipline?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="experimental-data">Experimental data</h3>
<ul>
<li>produced in a <strong>controlled</strong> setting (a laboratory or a clinical trial)</li>
<li>the researcher <strong>chooses</strong> the treatment</li>
<li>other factors are <strong>held fixed by design</strong></li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="non-experimental-observational-data">Non-experimental (observational) data</h3>
<ul>
<li><strong>not</strong> produced by controlled experiments on consumers, firms or countries</li>
<li>people <strong>choose</strong> their education, firms <strong>choose</strong> their prices, and so on</li>
<li>economic experiments are usually <strong>costly, unethical or impossible</strong></li>
</ul>
</div></div>
<div class="fragment">
<div title="The core challenge">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The core challenge</strong></p>
</div>
<div class="callout-content">
<p>Most economic data are <strong>observational</strong>. Econometrics develops methods that let us draw <strong>credible (causal) conclusions</strong> from such data. This is the main difference from the statistics used in the natural sciences.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="components-of-econometrics" class="slide level2">
<h2>Components of econometrics</h2>
<div class="columns">
<div class="column" style="width:48%;">
<div class="card">
<p><span class="ct">Inputs</span></p>
<ul>
<li>Economic <strong>theory</strong></li>
<li><strong>Mathematics</strong></li>
<li>Statistical <strong>theory</strong></li>
<li><strong>Data</strong></li>
<li><strong>Computers</strong> (R!)</li>
</ul>
</div>
</div><div class="column" style="width:4%;">
<p><span style="font-size:2em; color:#d9622b; display:block; margin-top:2.5em">→</span></p>
</div><div class="column" style="width:48%;">
<div class="card">
<p><span class="ct">Outputs</span></p>
<ul>
<li><strong>Estimation</strong>: how large is the effect?</li>
<li><strong>Inference</strong>: is the effect statistically significant?</li>
<li><strong>Forecasting / prediction</strong></li>
<li><strong>Evaluation</strong> of policies and interpretation</li>
</ul>
</div>
</div></div>
</section>
<section id="causal-questions-vs.-prediction" class="slide level2 smaller">
<h2>Causal questions vs.&nbsp;prediction</h2>
<p>Econometrics cares about <strong>both</strong> causal effects and prediction. Machine learning mostly cares about <strong>prediction</strong>.</p>
<div class="sorter" data-id="w1-sort-questions">
<div class="bins">
<div class="bin" data-bin="causal">
<p>Causal effect (“what if…?”)</p>
</div>
<div class="bin" data-bin="pred">
<p>Prediction / forecast</p>
</div>
</div>
<div class="items">
<p><span class="item" data-bin="causal">If the minimum wage rises by 10%, how much does employment change?</span> <span class="item" data-bin="pred">What will inflation be next month?</span> <span class="item" data-bin="causal">Does a smaller class size raise primary-school test scores?</span> <span class="item" data-bin="pred">Given a student’s high-school GPA, what college GPA should we expect?</span> <span class="item" data-bin="causal">What is the effect of a 1-point policy-rate hike on unemployment?</span> <span class="item" data-bin="pred">Which loan applicants are likely to default?</span> <span class="item" data-bin="causal">Does job training increase workers’ wages?</span></p>
</div>
</div>
<div class="tiny muted">
<p>Click a card, then click a box. Press <strong>Check</strong> when you are done.</p>
</div>
</section>
<section id="big-data-machine-learning-and-econometrics" class="slide level2 smaller">
<h2>Big data, machine learning and econometrics</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong>Big data</strong>: huge data sets from online activity, social media, transactions, …</li>
<li><strong>Data science</strong>: computer science + statistics + data mining + machine learning</li>
<li><strong>Machine learning</strong>: <em>“Given these attributes, what is the best prediction of y?”</em> It puts little or no emphasis on causation.</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>Econometrics</strong> deals with <strong>causal relationships <em>and</em> prediction</strong>:
<ul>
<li>How much does <span class="math inline">y</span> change <strong>if we change</strong> <span class="math inline">x</span>?</li>
<li>Is the effect <strong>statistically distinguishable</strong> from zero?</li>
<li>Would the effect hold <strong>ceteris paribus</strong>?</li>
</ul></li>
</ul>
</div></div>
<div title="Why this matters for you">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Why this matters for you</strong></p>
</div>
<div class="callout-content">
<p>The tools you learn here, above all regression, are the foundation for both applied economics and data science.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="the-steps-of-an-empirical-analysis" class="title-slide slide level1 section-slide center">
<h1>The steps of an empirical analysis</h1>
<p>From a question to an answer: economic model, econometric model, data, estimation, testing.</p>
</section>
<section id="from-a-question-to-an-answer" class="slide level2">
<h2>From a question to an answer</h2>
<div class="flow">
<div class="step fragment">
<p><span class="n">1</span> <strong>Question</strong> Pose it precisely</p>
</div>
<div class="step fragment">
<p><span class="n">2</span> <strong>Economic model</strong> Theory: utility or profit maximization, …</p>
</div>
<div class="step fragment">
<p><span class="n">3</span> <strong>Econometric model</strong> Functional form + error term</p>
</div>
<div class="step fragment">
<p><span class="n">4</span> <strong>Data</strong> Collect or obtain data</p>
</div>
<div class="step fragment">
<p><span class="n">5</span> <strong>Estimation</strong> Estimate the unknown parameters</p>
</div>
<div class="step fragment">
<p><span class="n">6</span> <strong>Inference</strong> Test hypotheses</p>
</div>
<div class="step fragment">
<p><span class="n">7</span> <strong>Use</strong> Prediction and policy analysis</p>
</div>
</div>
<div class="fragment">
<p>Example questions with <strong>policy relevance</strong>:</p>
<ul>
<li>How does <strong>class size</strong> affect student performance in primary schools?</li>
<li>If the <strong>minimum wage</strong> rises by 10%, how much does unemployment change?</li>
<li>If the <strong>punishment</strong> for certain crimes becomes more severe, do crime rates fall on average?</li>
</ul>
</div>
</section>
<section id="step-2-an-economic-model-of-crime-becker" class="slide level2 smaller">
<h2>Step 2: an economic model of crime (Becker)</h2>
<p>Gary <strong>Becker</strong> (Nobel Prize, 1992) used utility maximization to study topics once considered outside economics: crime, discrimination, the family, …</p>
<p>An individual decides how much <strong>time</strong> to spend on illegal activity. This gives a <em>supply function</em>:</p>
<p><span class="math display">
y = f(x_1, x_2, x_3, x_4, x_5, x_6, x_7)
</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="math inline">y</span>: hours spent in criminal activities</li>
<li><span class="math inline">x_1</span>: “wage” for an hour of criminal activity</li>
<li><span class="math inline">x_2</span>: hourly wage in legal employment</li>
<li><span class="math inline">x_3</span>: other income</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="math inline">x_4</span>: probability of getting caught</li>
<li><span class="math inline">x_5</span>: probability of conviction if caught</li>
<li><span class="math inline">x_6</span>: expected sentence if convicted</li>
<li><span class="math inline">x_7</span>: age</li>
</ul>
</div></div>
<div class="fragment">
<p>The <strong>functional form</strong> <span class="math inline">f(\cdot)</span> is not specified. Theory tells us <em>which</em> factors matter and often in which <em>direction</em>, but not <strong>how much</strong>.</p>
</div>
</section>
<section id="step-3-from-an-economic-to-an-econometric-model" class="slide level2 smaller">
<h2>Step 3: from an economic to an econometric model</h2>
<p><strong>Job training and worker productivity.</strong> Economic model: <span class="math inline">\;wage = f(educ,\ exper,\ training)</span></p>
<p>Choose a <strong>linear</strong> specification and add an <strong>error term</strong>. Click on each part:</p>
<div class="hotspots">
<p><span class="math display">
\Large wage = \color{#1f5fa8}{\beta_0} + \color{#1f5fa8}{\beta_1}\, educ + \color{#1f5fa8}{\beta_2}\, exper + \color{#d9622b}{\beta_3}\, training + \color{#c0392b}{u}
</span></p>
<div class="chips">
<p><span data-tip="<b>Dependent variable.</b> Hourly wage in dollars. It is the variable we want to explain."><span class="math inline">wage</span></span> · <span data-tip="<b>Parameters.</b> Unknown constants that describe the direction and strength of each relationship. We must <b>estimate</b> them from data."><span class="math inline">\beta_0,\ \beta_1,\ \beta_2</span></span> · <span data-tip="<b>The parameter of interest.</b> It is the effect of one more week of training on the wage, holding educ, exper and u fixed. The hypothesis H<sub>0</sub>: β<sub>3</sub> = 0 says that training has no effect."><span class="math inline">\beta_3</span></span> · <span data-tip="<b>Explanatory variables.</b> Years of education, years of experience, weeks of job training. These are observed factors."><span class="math inline">educ,\ exper,\ training</span></span> · <span data-tip="<b>Error (disturbance) term.</b> It collects all unobserved factors, such as innate ability, quality of education and family background. We can never remove u completely, because no model is fully deterministic."><span class="math inline">u</span></span></p>
</div>
<div class="tip-panel">
<p>Click a highlighted part to see what it means.</p>
</div>
</div>
<div class="fragment">
<div title="Key point">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<p>Dealing with the <strong>unobserved error term <span class="math inline">u</span></strong> is the central issue in almost all of econometrics.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="check-your-understanding" class="slide level2">
<h2>Check your understanding</h2>
<div class="quiz" data-id="w1-u" data-answer="b">
<p><strong>In the econometric model <span class="math inline">wage = \beta_0 + \beta_1 educ + \beta_2 exper + \beta_3 training + u</span>, which of the following belongs in <span class="math inline">u</span>?</strong></p>
<p><span data-opt="a">A) Years of experience</span></p>
<p><span data-opt="b">B) The worker’s innate ability</span></p>
<p><span data-opt="c">C) The parameter <span class="math inline">\beta_3</span></span></p>
<p><span data-opt="d">D) The hourly wage</span></p>
<div class="explain">
<p><strong>Ability</strong> is not observed in a typical data set, so it becomes part of the error term. Experience is an observed regressor, <span class="math inline">\beta_3</span> is a parameter and the wage is the dependent variable. Later we will ask: <em>is ability correlated with education?</em> If it is, we have a problem.</p>
</div>
</div>
</section></section>
<section>
<section id="types-of-economic-data" class="title-slide slide level1 section-slide center">
<h1>Types of economic data</h1>
<p>Cross-sectional, time series, pooled cross sections and panel data — and what each one lets us do.</p>
</section>
<section id="cross-sectional-data" class="slide level2 smaller">
<h2>1 · Cross-sectional data</h2>
<p>A sample of <strong>individuals, households, firms, cities, countries, …</strong> taken at <strong>one point in time</strong>.</p>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li>Key feature: <strong>random sampling</strong> from a population</li>
<li>Order of observations does not matter</li>
<li>Sources: official records, surveys, questionnaires. One example is the TÜİK household labor force survey.</li>
</ul>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wage1[, <span class="fu">c</span>(<span class="st">"wage"</span>, <span class="st">"educ"</span>, <span class="st">"exper"</span>,</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a>               <span class="st">"female"</span>, <span class="st">"married"</span>)], <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;   wage educ exper female married
#&gt; 1 3.10   11     2      1       0
#&gt; 2 3.24   12    22      1       1
#&gt; 3 3.00   11     2      0       0
#&gt; 4 6.00    8    44      0       1
#&gt; 5 5.30   12     7      0       1
#&gt; 6 8.75   16     9      0       1</code></pre>
</div>
</div>
</div></div>
</section>
<section id="time-series-data" class="slide level2 smaller">
<h2>2 · Time series data</h2>
<p>Observations on one or more variables <strong>over time</strong>, in <strong>chronological order</strong>. The frequency can be daily, monthly, quarterly or annual.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"phillips"</span>)   <span class="co"># U.S. annual data, 1948-2003</span></span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(phillips, <span class="fu">aes</span>(year)) <span class="sc">+</span></span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> unem, <span class="at">color =</span> <span class="st">"Unemployment rate"</span>), <span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> inf,  <span class="at">color =</span> <span class="st">"Inflation rate"</span>),   <span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"percent"</span>, <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="01-introduction_files/figure-revealjs/unnamed-chunk-2-1.png" width="975"></p>
</figure>
</div>
</div>
</div></div>
<div class="tiny muted">
<p>Past values often affect current values (<em>persistence</em>), so observations are <strong>not</strong> independent. Time series are the topic of <strong>Econometrics II</strong>.</p>
</div>
</section>
<section id="pooled-cross-sections-4-panel-data" class="slide level2 smaller">
<h2>3 · Pooled cross sections &amp; 4 · Panel data</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="pooled-cross-section">Pooled cross section</h3>
<p><strong>Different</strong> random samples drawn in different years and <strong>combined</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"hprice3"</span>)  <span class="co"># houses sold in 1978 and 1981</span></span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(hprice3<span class="sc">$</span>year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; 1978 1981 
#&gt;  179  142</code></pre>
</div>
</div>
<p>The same houses are <strong>not</strong> followed over time.</p>
</div><div class="column" style="width:50%;">
<h3 id="panel-longitudinal-data">Panel (longitudinal) data</h3>
<p>The <strong>same</strong> units are followed over time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"crime2"</span>)  <span class="co"># 46 cities, 1982 &amp; 1987</span></span>
<span id="cb6-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crime2[, <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"crimes"</span>, <span class="st">"unem"</span>)], <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;   year crimes unem
#&gt; 1   82  17136  8.2
#&gt; 2   87  17306  3.7
#&gt; 3   82  75654  8.1
#&gt; 4   87  83960  5.4</code></pre>
</div>
</div>
<ul>
<li><strong>Micro panels:</strong> large <span class="math inline">N</span>, small <span class="math inline">T</span> (households, firms)</li>
<li><strong>Macro panels:</strong> small <span class="math inline">N</span>, large <span class="math inline">T</span> (countries)</li>
</ul>
</div></div>
</section>
<section id="your-turn-classify-the-data-sets" class="slide level2 smaller">
<h2>Your turn: classify the data sets</h2>
<div class="sorter" data-id="w1-sort-data">
<div class="bins">
<div class="bin" data-bin="cs">
<p>Cross-section</p>
</div>
<div class="bin" data-bin="ts">
<p>Time series</p>
</div>
<div class="bin" data-bin="pool">
<p>Pooled cross-section</p>
</div>
<div class="bin" data-bin="panel">
<p>Panel</p>
</div>
</div>
<div class="items">
<p><span class="item" data-bin="cs">Wages &amp; education of 526 workers surveyed in 1976</span> <span class="item" data-bin="ts">Monthly USD/TRY exchange rate, 2003–2025</span> <span class="item" data-bin="pool">TÜİK household budget surveys of 2010 and 2020 (new households each year)</span> <span class="item" data-bin="panel">GDP per capita of 30 OECD countries, 1960–2020</span> <span class="item" data-bin="ts">Daily closing values of BIST-100</span> <span class="item" data-bin="cs">Test scores of 420 school districts in one year</span> <span class="item" data-bin="panel">The same 1,000 firms’ balance sheets, 2015–2024</span> <span class="item" data-bin="pool">House sales in 1978 and a new random sample in 1981</span></p>
</div>
</div>
</section></section>
<section>
<section id="causality-and-ceteris-paribus" class="title-slide slide level1 section-slide center">
<h1>Causality and <em>ceteris paribus</em></h1>
<p>Why correlation is not causation, and what would have to be true for a regression to be causal.</p>
</section>
<section id="correlation-is-not-causation" class="slide level2">
<h2>Correlation is not causation</h2>
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li>In economics we usually want to know whether <span class="math inline">x</span> has a <strong>causal effect</strong> on <span class="math inline">y</span>.</li>
<li>A <strong>correlation</strong> may suggest a causal link, but it cannot <strong>prove</strong> one.</li>
<li><em>The rooster crows every morning before sunrise. The two events are highly correlated, but the rooster does not make the sun rise.</em></li>
</ul>
<p>. . .</p>
<p><strong>Ceteris paribus</strong> means “other relevant factors being equal”, or <strong>holding all other factors fixed</strong>.</p>
<p>Most economic questions are <strong><em>ceteris paribus</em> questions</strong> by nature.</p>
</div><div class="column" style="width:45%;">
<div title="Demand example">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Demand example</strong></p>
</div>
<div class="callout-content">
<p>What is the effect of a price change on quantity demanded, <strong>holding income, the prices of other goods and tastes fixed</strong>?</p>
<p>If the other factors are not held fixed, we cannot tell what the causal effect of the price is.</p>
</div>
</div>
</div>
</div>
<p><strong>The key question in any analysis:</strong> <em>Have we held enough other factors fixed?</em></p>
</div></div>
</section>
<section id="interactive-how-an-unobserved-factor-fools-us" class="slide level2 smaller">
<h2>Interactive: how an unobserved factor fools us</h2>
<p><strong>Education → wage</strong>, but <strong>ability</strong> affects <em>both</em> education and wage, and ability is <strong>unobserved</strong>. Move the sliders:</p>
<div class="widget" data-widget="confounding">

</div>
<div class="tiny muted">
<p>Try this: (1) set <em>ability → educ</em> to 0; (2) set <em>true effect β</em> to 0 and look at the orange line; (3) turn on the experiment.</p>
</div>
<aside class="notes">
<p>Discussion prompts. With β = 0 the naive line still slopes up, because more able people get more schooling. The experiment switch assigns education at random, which breaks the link. This is why randomized experiments are the benchmark.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-1-fertilizer-and-crop-yield" class="slide level2 smaller">
<h2>Example 1: fertilizer and crop yield</h2>
<p><strong>Question:</strong> What is the effect of fertilizer on wheat yield?</p>
<ul>
<li>Other factors also matter: rainfall, soil quality, parasites, …</li>
<li><strong>Experiment:</strong> divide land into equal plots, apply <strong>different amounts</strong> of fertilizer to each plot and measure the yield.</li>
<li>This gives a <strong>cross-sectional data set</strong>, where the unit of observation is a plot.</li>
</ul>
<div class="fragment">
<div title="When does this measure the ceteris paribus effect?">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>When does this measure the ceteris paribus effect?</strong></p>
</div>
<div class="callout-content">
<p>When the fertilizer amounts are assigned <strong>independently of other plot characteristics</strong>, such as soil quality. We do not even need to observe soil quality. We only need the assignment to <strong>ignore</strong> it.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="check-fertilizer-on-the-best-plots" class="slide level2">
<h2>Check: fertilizer on the best plots</h2>
<div class="quiz" data-id="w1-fert" data-answer="b">
<p><strong>A farmer puts <em>more</em> fertilizer on the <em>best</em> plots. The estimated effect of fertilizer will most likely be…</strong></p>
<p><span data-opt="a">A) about right</span></p>
<p><span data-opt="b">B) too large, because good soil raises yields too</span></p>
<p><span data-opt="c">C) too small</span></p>
<div class="explain">
<p>Soil quality is positively related to both fertilizer and yield. Part of the soil effect is then attributed to fertilizer, and the effect is <strong>overstated</strong>. It is the same mechanism as ability in the wage example.</p>
</div>
</div>
</section>
<section id="example-2-the-return-to-education" class="slide level2 smaller">
<h2>Example 2: the return to education</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Question:</strong> If a person is given <strong>one more year</strong> of education, by how much will his or her wage rise, <em>holding everything else fixed</em>?</p>
<p><strong>An ideal (hypothetical) experiment:</strong></p>
<ol type="1">
<li>A social planner draws a random group of people.</li>
<li>The planner <strong>randomly assigns</strong> each person a level of education.</li>
<li>Years later, the planner measures their wages.</li>
</ol>
<p>This is a <strong>randomized controlled trial (RCT)</strong>. Here education would be <strong>unrelated</strong> to ability.</p>
</div><div class="column" style="width:45%;">
<div title="But…">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>But…</strong></p>
</div>
<div class="callout-content">
<p>The experiment is <strong>impossible</strong>, for ethical and practical reasons. Imagine assigning random schooling to 6-year-olds!</p>
</div>
</div>
</div>
</div>
<p><strong>Reality:</strong> people <strong>choose</strong> their education, so</p>
<ul>
<li>more able people tend to get <strong>more education</strong>, and</li>
<li>more able people tend to earn <strong>higher wages</strong>.</li>
</ul>
<p>It is hard to separate the effect of education from the effect of <strong>ability</strong>.</p>
</div></div>
</section>
<section id="example-3-police-and-city-crime" class="slide level2 smaller">
<h2>Example 3: police and city crime</h2>
<p><strong>Question:</strong> If a city is randomly given 10 more police officers, by how much would its crime rate fall?</p>
<ul>
<li>We cannot find two cities that are identical in every respect, and we don’t need to. We need to know whether the data can be treated <strong>as if</strong> they came from an experiment.</li>
<li>In practice the police force is chosen by city authorities, who <strong>look at crime</strong> when they make the decision.</li>
</ul>
<div class="fragment">
<div title="Simultaneity">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Simultaneity</strong></p>
</div>
<div class="callout-content">
<p>Does the police force affect crime, <strong>or does crime affect the size of the police force?</strong> The two are determined <strong>simultaneously</strong>. This is another reason why a simple correlation can be very misleading.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="activity">
<p><span class="label">Think – Pair – Share</span></p>
<p>Name <strong>one</strong> unobserved factor that could bias the simple relationship between <em>police per capita</em> and <em>crime rate</em>. What is the direction of the bias?</p>
<div class="timer" data-seconds="90">

</div>
</div>
</div>
</section></section>
<section>
<section id="experiments-the-gold-standard" class="title-slide slide level1 section-slide center">
<h1>Experiments: the gold standard</h1>
<p>Randomized experiments, why randomization works, and the quasi-experiments we use instead.</p>
</section>
<section id="randomized-controlled-trials-rcts" class="slide level2 smaller">
<h2>Randomized controlled trials (RCTs)</h2>
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li>Subjects are <strong>randomly</strong> assigned to a <strong>treatment group</strong> and a <strong>control group</strong>.</li>
<li>Because of randomization, the groups are <strong>the same on average</strong> in <em>every</em> respect, observed or not, except for the treatment.</li>
<li>The difference in mean outcomes then estimates the <strong>average treatment effect (ATE)</strong>.</li>
<li>Used routinely in medicine, and increasingly in economics, psychology and sociology.</li>
</ul>
</div><div class="column" style="width:45%;">
<div title="The crucial ingredient">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The crucial ingredient</strong></p>
</div>
<div class="callout-content">
<p><strong>Randomization.</strong> Without it, the groups may differ systematically (<em>selection bias</em>).</p>
</div>
</div>
</div>
</div>
<ul>
<li><strong>Internal validity:</strong> do the conditions for a causal conclusion hold here?</li>
<li><strong>External validity:</strong> can the results be generalized to other settings?</li>
</ul>
</div></div>
</section>
<section id="interactive-why-randomization-works" class="slide level2 smaller">
<h2>Interactive: why randomization works</h2>
<p>Each dot is a person. <strong>Motivation</strong> is unobserved and raises the outcome. Compare self-selection with a coin flip:</p>
<div class="widget" data-widget="rct">

</div>
<aside class="notes">
<p>Under self-selection, motivated people choose treatment, and the estimate is about 2 + 1.5 × (imbalance). Under a coin flip, individual assignments may be unlucky, but the histogram centers on 2. That is unbiasedness, which we formalize in Week 3.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="rct-examples" class="slide level2 smaller">
<h2>RCT examples</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="do-diets-work">Do diets work?</h3>
<ul>
<li>Randomly assign obese individuals to specific diets (Atkins, Ornish, …).</li>
<li>Record weight and other characteristics <strong>before</strong> the diet.</li>
<li>Follow the individuals for a year or longer and measure again.</li>
<li><span class="math inline">H_0</span>: no difference in average weight; <span class="math inline">H_1</span>: sticking to the diet reduces weight.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="pakistan-early-child-development-scale-up-trial">Pakistan Early Child Development Scale-Up Trial</h3>
<ul>
<li><strong>Control group:</strong> basic health and nutrition services</li>
<li><strong>Group I:</strong> enhanced nutrition</li>
<li><strong>Group II:</strong> early child development (coaching, visits)</li>
<li><strong>Group III:</strong> both interventions</li>
<li>At 24 months, <strong>all three</strong> treated groups had significantly higher cognitive, language and motor scores.</li>
</ul>
</div></div>
</section>
<section id="quasi-experiments-natural-experiments" class="slide level2 smaller">
<h2>Quasi-experiments (natural experiments)</h2>
<p>When randomization is not possible:</p>
<ul>
<li>There is still a <strong>treatment</strong> group and a <strong>comparison</strong> group, but <strong>without random assignment</strong>.</li>
<li>Outcomes can often be measured <strong>before and after</strong> the intervention.</li>
<li><strong>Program evaluation</strong> estimates the effect of a program, policy or intervention.</li>
</ul>
<div class="fragment">
<p>Widely used quasi-experimental methods, which you will meet in later courses:</p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Matched-pair analysis</li>
<li>Propensity score matching</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>Difference-in-differences</strong></li>
<li><strong>Regression discontinuity</strong> designs</li>
</ul>
</div></div>
<div title="Where this course fits">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Where this course fits</strong></p>
</div>
<div class="callout-content">
<p>In Econometrics I we learn <strong>multiple regression</strong>, which lets us hold observed factors fixed <em>explicitly</em>. This is our main tool for <em>ceteris paribus</em> analysis with observational data.</p>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="a-first-look-at-r" class="title-slide slide level1 section-slide center">
<h1>A first look at R</h1>
<p>A first regression, a first prediction, and a warning about reading it causally.</p>
</section>
<section id="predicting-college-gpa-from-high-school-gpa" class="slide level2 smaller">
<h2>Predicting college GPA from high-school GPA</h2>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"gpa1"</span>)</span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gpa1, <span class="fu">aes</span>(hsGPA, colGPA)) <span class="sc">+</span></span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">6</span>, <span class="at">color =</span> <span class="st">"#1f5fa8"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb8-5"><a aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"#d9622b"</span>, <span class="at">linewidth =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"High-school GPA"</span>, <span class="at">y =</span> <span class="st">"College GPA"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="01-introduction_files/figure-revealjs/unnamed-chunk-5-1.png" width="900"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section id="try-it-a-first-prediction" class="slide level2">
<h2>Try it: a first prediction</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(colGPA <span class="sc">~</span> hsGPA, <span class="at">data =</span> gpa1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)       hsGPA 
#&gt;   1.4154336   0.4824346</code></pre>
</div>
</div>
<p>The estimated line is <span class="math inline">\widehat{colGPA} = 1.415 + 0.482\, hsGPA</span>.</p>
<div class="numq" data-id="w1-pred" data-answer="2.862" data-tol="0.01">
<p><strong>What college GPA do we predict for a student with a high-school GPA of 3.0?</strong></p>
<div class="explain">
<p><span class="math inline">1.415 + 0.482 \times 3 = 2.862</span>. Next week we will see <strong>how</strong> these two numbers are chosen (ordinary least squares) and what they mean.</p>
</div>
</div>
</section>
<section id="prediction-is-not-causation" class="slide level2">
<h2>Prediction is not causation</h2>
<div class="quiz" data-id="w1-pred2" data-answer="a">
<p><strong>Does this line tell us that raising a student’s high-school GPA by 1 point <em>causes</em> college GPA to rise by 0.48?</strong></p>
<p><span data-opt="a">A) Not necessarily. Motivation or ability could drive both.</span></p>
<p><span data-opt="b">B) Yes, the regression proves it.</span></p>
<div class="explain">
<p>Good for <strong>prediction</strong> does not mean <strong>causal</strong>. Unobserved factors such as study habits or ability probably affect both GPAs.</p>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key takeaways</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ol type="1">
<li>Econometrics uses <strong>theory + data + statistics</strong> to <strong>measure</strong> economic relationships.</li>
<li>Most economic data are <strong>observational</strong>, so we need special methods.</li>
<li><strong>Economic model → econometric model</strong>: choose a functional form and add an error term <span class="math inline">u</span>.</li>
<li>Data types: <strong>cross-section, time series, pooled cross-section, panel</strong>.</li>
<li>The central question: can we interpret a relationship <strong><em>ceteris paribus</em></strong>, that is, <strong>causally</strong>?</li>
<li><strong>Randomization</strong> breaks the link between the treatment and unobserved factors.</li>
</ol>
</div><div class="column" style="width:40%;">
<div class="card">
<p><span class="ct">Next topic</span></p>
<p><strong>Simple regression model I</strong>: estimating <span class="math inline">y = \beta_0 + \beta_1 x + u</span> by Ordinary Least Squares.</p>
<p><span class="tag">Wooldridge ch.&nbsp;2</span> <span class="tag">Heiss ch.&nbsp;2</span></p>
</div>
<div class="score-box">

</div>
</div></div>
<script src="assets/deck01.js"></script>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Econometrics I · Yıldız Technical University</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"numbers":true},
'chalkboard': {"buttons":true,"theme":"whiteboard","boardmarkerWidth":3},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 760,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>