<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan">
  <title>Econometrics I – Multiple Regression Analysis I</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-70fcdf68ba588c6f83f9e4af10fa12ef.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- shared interactive layer for all Econometrics I decks -->
  <script src="assets/wooldridge-data.js"></script>
  <script src="assets/hmda-data.js"></script>
  <script src="assets/econ-core.js"></script>
  <script src="assets/econ-ui.js"></script>
  <script src="assets/widgets-shared.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Multiple Regression Analysis I</h1>
  <p class="subtitle">Topic 4 · Estimation, omitted variable bias and the Gauss–Markov theorem</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan 
</div>
        <p class="quarto-title-affiliation">
            Yıldız Technical University · Department of Economics
          </p>
    </div>
</div>

  <p class="date">Fall 2026</p>
</section>
<section id="todays-roadmap" class="slide level2">
<h2>Today’s roadmap</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="objectives">
<p><strong>By the end of this lecture you should be able to</strong></p>
<ul>
<li>explain why we need <strong>more than one</strong> explanatory variable</li>
<li>interpret multiple regression coefficients <strong><em>ceteris paribus</em></strong></li>
<li>describe OLS as fitting a <strong>plane</strong> and explain <strong>partialling out</strong></li>
<li>state <strong>MLR.1–MLR.5</strong>, <strong>unbiasedness</strong> and <strong>Gauss–Markov</strong></li>
<li>derive the sign of <strong>omitted variable bias</strong> and explain <strong>multicollinearity</strong></li>
</ul>
</div>
</div><div class="column" style="width:45%;">
<div class="card">
<p><span class="ct">Reading</span></p>
<p><span class="tag weektag">Fall 2026 · Week 4</span></p>
<p><span class="tag">Wooldridge ch.&nbsp;3</span> <span class="tag">Heiss ch.&nbsp;3</span> <span class="tag">Stock &amp; Watson ch.&nbsp;6</span></p>
</div>
<div class="card">
<p><span class="ct">Lab</span></p>
<p>Multiple regression in R. See <em>Lab 05</em>.</p>
</div>
<div class="card">
<p><span class="ct">Last week</span></p>
<p>SLR.4 is hard to believe when <span class="math inline">u</span> hides important factors.</p>
</div>
</div></div>
</section>
<section id="warm-up-a-coefficient-that-shrinks" class="slide level2">
<h2>Warm-up: a coefficient that shrinks</h2>
<p><code>gpa1</code> (141 students): college GPA on the ACT score, with and without high-school GPA.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">ACT alone</span></p>
<p><span class="math inline">\widehat{colGPA} = 2.40 + \mathbf{0.0271}\,ACT</span></p>
</div>
</div><div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">ACT and high-school GPA</span></p>
<p><span class="math inline">\widehat{colGPA} = 1.29 + 0.453\,hsGPA + \mathbf{0.0094}\,ACT</span></p>
</div>
</div></div>
<div class="quiz" data-id="w4-warmup" data-answer="b">
<p><strong>The ACT coefficient falls to about one-third after adding hsGPA. Why?</strong></p>
<p><span data-opt="a">A) Adding a variable always makes the other coefficients smaller</span></p>
<p><span data-opt="b">B) High-ACT students also tend to have high hsGPA, so ACT alone picked up part of its effect</span></p>
<p><span data-opt="c">C) The second regression uses fewer observations</span></p>
<div class="explain">
<p>ACT and hsGPA are correlated (0.35), so alone ACT “gets credit” for hsGPA. Multiple regression compares students with the <strong>same</strong> hsGPA.</p>
</div>
</div>
</section>
<section>
<section id="why-multiple-regression" class="title-slide slide level1 section-slide center">
<h1>Why multiple regression?</h1>
<p>Holding other factors fixed <strong>explicitly</strong>, and more flexible functional forms.</p>
</section>
<section id="holding-other-factors-fixed-explicitly" class="slide level2 smaller">
<h2>Holding other factors fixed <em>explicitly</em></h2>
<ul>
<li>In simple regression, SLR.4 requires that <strong>all</strong> other factors in <span class="math inline">u</span> are unrelated to <span class="math inline">x</span>. This is often unrealistic.</li>
<li>Multiple regression lets us <strong>control</strong> for other observed factors that affect <span class="math inline">y</span>.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">Wage equation</span></p>
<p><span class="math display">wage = \beta_0 + \beta_1 educ + \beta_2 exper + u</span></p>
<p><span class="math inline">\beta_1</span>: the effect of education <strong>holding experience fixed</strong>.</p>
</div>
</div><div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">Test scores</span></p>
<p><span class="math display">avgscore = \beta_0 + \beta_1 expend + \beta_2 avginc + u</span></p>
<p>Omitting <span class="math inline">avginc</span> would put it in <span class="math inline">u</span>, and it is correlated with spending.</p>
</div>
</div></div>
<div class="fragment">
<p>Multiple regression also allows <strong>more flexible functional forms</strong>:</p>
<p><span class="math display">
cons = \beta_0 + \beta_1 inc + \beta_2 inc^2 + u \qquad\Rightarrow\qquad \frac{\Delta cons}{\Delta inc} \approx \beta_1 + 2\beta_2\, inc
</span></p>
<p>The marginal propensity to consume now <strong>depends on income</strong>. Here we cannot “hold <span class="math inline">inc^2</span> fixed” while changing <span class="math inline">inc</span>.</p>
</div>
</section>
<section id="the-model-with-k-explanatory-variables" class="slide level2 smaller">
<h2>The model with <span class="math inline">k</span> explanatory variables</h2>
<div class="hotspots">
<p><span class="math display">
\Large y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k + u
</span></p>
<div class="chips">
<p><span data-tip="<b>Intercept</b>: the predicted y when all x's are zero. It is often not meaningful on its own."><span class="math inline">\beta_0</span></span> <span data-tip="<b>Partial effect</b>: the change in y when x<sub>j</sub> increases by one unit, <b>holding all other x's and u fixed</b>. This is the ceteris paribus effect."><span class="math inline">\beta_j</span></span> <span data-tip="<b>k explanatory variables.</b> They can be different factors or functions of the same factor (logs, squares, …)."><span class="math inline">x_1,\dots,x_k</span></span> <span data-tip="<b>Error term</b>: all other factors affecting y that are not in the model."><span class="math inline">u</span></span></p>
</div>
<div class="tip-panel">
<p>Click each symbol.</p>
</div>
</div>
<div class="fragment">
<p><strong>Key assumption, MLR.4 (zero conditional mean):</strong></p>
<p><span class="math display">
E(u \mid x_1, x_2, \dots, x_k) = 0
</span></p>
<p>For every combination of the <span class="math inline">x</span>’s, the unobservables average to zero. For example, in the wage equation average <strong>ability</strong> must be the same for all combinations of <span class="math inline">educ</span> and <span class="math inline">exper</span>.</p>
</div>
</section></section>
<section>
<section id="ols-estimation" class="title-slide slide level1 section-slide center">
<h1>OLS estimation</h1>
<p>The same minimization in more dimensions: fitting a plane, partialling out, goodness of fit.</p>
</section>
<section id="same-principle-more-dimensions" class="slide level2 smaller">
<h2>Same principle, more dimensions</h2>
<p>The <strong>sample regression function</strong> is <span class="math inline">\;\hat y = \hat\beta_0 + \hat\beta_1 x_1 + \dots + \hat\beta_k x_k</span></p>
<p>OLS chooses the <span class="math inline">k+1</span> estimates to minimize the sum of squared residuals:</p>
<p><span class="math display">
\min_{\hat\beta_0,\dots,\hat\beta_k}\; \sum_{i=1}^n \big(y_i - \hat\beta_0 - \hat\beta_1 x_{i1} - \dots - \hat\beta_k x_{ik}\big)^2
</span></p>
<div class="fragment">
<p>This gives <strong><span class="math inline">k+1</span> first-order conditions</strong>, the sample versions of <span class="math inline">E(u)=0</span> and <span class="math inline">E(x_j u)=0</span>:</p>
<p><span class="math display">
\sum_{i=1}^n \hat u_i = 0, \qquad \sum_{i=1}^n x_{ij}\,\hat u_i = 0 \quad (j = 1,\dots,k)
</span></p>
</div>
<div class="fragment">
<div title="Geometry">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Geometry</strong></p>
</div>
<div class="callout-content">
<p>With <strong>one</strong> regressor OLS fits a <strong>line</strong>. With <strong>two</strong> regressors it fits a <strong>plane</strong> in 3D space. With <span class="math inline">k</span> regressors it fits a hyperplane that we can no longer draw.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="interactive-ols-fits-a-plane" class="slide level2 smaller">
<h2>Interactive: OLS fits a plane</h2>
<p>Drag the picture to rotate it. First fit the plane <strong>yourself</strong> with the sliders, then switch to <strong>OLS</strong>.</p>
<div class="widget" data-widget="ols-3d">

</div>
<aside class="notes">
<p>Suggested use. (1) Simulated data, “your guess”: start with the flat plane at the mean of y and let students tilt it along x1 and x2 to reduce the SSR. (2) Switch to OLS: the residuals are the vertical distances to the plane, and blue and orange points balance each other. (3) Turn on the true PRF (simulation only) and point out that the OLS plane is close to it but not equal. In practice we never see the PRF. (4) gpa1: the plane rises steeply along hsGPA and is almost flat along ACT.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="interpreting-the-estimates" class="slide level2 smaller">
<h2>Interpreting the estimates</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"gpa1"</span>)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(colGPA <span class="sc">~</span> hsGPA <span class="sc">+</span> ACT, <span class="at">data =</span> gpa1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)       hsGPA         ACT 
#&gt; 1.286327767 0.453455885 0.009426012</code></pre>
</div>
</div>
<p><span class="math display">
\widehat{colGPA} = 1.29 + 0.453\, hsGPA + 0.0094\, ACT, \qquad n = 141
</span></p>
<div class="fragment">
<ul>
<li><strong>Holding ACT fixed</strong>, one more point of hsGPA raises the predicted colGPA by <strong>0.453</strong>, almost half a point.</li>
<li>Equivalently: take two students <strong>A and B with the same ACT score</strong>. If A’s hsGPA is one point higher, we predict A’s colGPA to be 0.453 higher.</li>
<li>The intercept 1.29 is the prediction for hsGPA = 0 and ACT = 0. No such student exists, so it has no useful interpretation.</li>
</ul>
</div>
</section>
<section id="check-the-effect-of-act" class="slide level2">
<h2>Check: the effect of ACT</h2>
<div class="quiz" data-id="w4-interp" data-answer="c">
<p><strong>Holding hsGPA fixed, a 10-point higher ACT score predicts a college GPA that is higher by about…</strong></p>
<p><span data-opt="a">A) 0.453</span></p>
<p><span data-opt="b">B) 0.271</span></p>
<p><span data-opt="c">C) 0.094</span></p>
<div class="explain">
<p><span class="math inline">10 \times 0.0094 = 0.094</span>: a small effect. The simple-regression value <span class="math inline">10\times 0.0271 = 0.271</span> does not hold hsGPA fixed.</p>
</div>
</div>
</section>
<section id="changing-several-variables-at-once" class="slide level2 smaller">
<h2>Changing several variables at once</h2>
<p><span class="math display">
\widehat{\log(wage)} = 0.284 + 0.092\, educ + 0.0041\, exper + 0.022\, tenure, \qquad n = 526
</span></p>
<ul>
<li>Holding <span class="math inline">exper</span> and <span class="math inline">tenure</span> fixed, one more year of education raises the wage by about <strong>9.2%</strong>.</li>
</ul>
<div class="fragment">
<p>If a worker stays <strong>one more year with the same employer</strong>, both <span class="math inline">exper</span> and <span class="math inline">tenure</span> rise by 1:</p>
<div class="numq" data-id="w4-both" data-answer="2.61" data-tol="0.02">
<p><strong>By about how many percent does the predicted wage change? (Enter a number such as 2.5.)</strong></p>
<div class="explain">
<p><span class="math inline">\Delta\widehat{\log(wage)} = 0.0041\,\Delta exper + 0.022\,\Delta tenure = 0.0041 + 0.022 = 0.0261</span>, so about <strong>2.61%</strong>.</p>
</div>
</div>
</div>
</section>
<section id="fitted-values-residuals-and-their-properties" class="slide level2 smaller">
<h2>Fitted values, residuals and their properties</h2>
<p><span class="math display">
\hat y_i = \hat\beta_0 + \hat\beta_1 x_{i1} + \dots + \hat\beta_k x_{ik}, \qquad \hat u_i = y_i - \hat y_i
</span></p>
<ul>
<li><span class="math inline">\hat u_i &gt; 0</span>: the model <strong>under</strong>-predicts <span class="math inline">y_i</span>. <span class="math inline">\hat u_i &lt; 0</span>: it <strong>over</strong>-predicts.</li>
</ul>
<p>The algebraic properties from simple regression carry over:</p>
<ol type="1">
<li><span class="math inline">\sum_i \hat u_i = 0</span>, so <span class="math inline">\bar{\hat u} = 0</span> and <span class="math inline">\bar y = \bar{\hat y}</span></li>
<li><span class="math inline">\sum_i x_{ij}\hat u_i = 0</span> for <strong>every</strong> <span class="math inline">j</span>: the residuals are uncorrelated with each regressor</li>
<li>The point of means <span class="math inline">(\bar x_1, \dots, \bar x_k, \bar y)</span> lies on the regression plane</li>
</ol>
</section>
<section id="partialling-out" class="slide level2 smaller">
<h2>“Partialling out”</h2>
<p>With two regressors, the OLS slope on <span class="math inline">x_1</span> can be written as</p>
<p><span class="math display">
\hat\beta_1 = \frac{\sum_i \hat r_{i1}\, y_i}{\sum_i \hat r_{i1}^2}
</span></p>
<p>where <span class="math inline">\hat r_{i1}</span> are the residuals from regressing <span class="math inline">x_1</span> on <span class="math inline">x_2</span>: the part of <span class="math inline">x_1</span> <strong>not explained by <span class="math inline">x_2</span></strong>.</p>
<div class="widget" data-widget="fwl">

</div>
</section>
<section id="simple-vs.-multiple-regression-estimates" class="slide level2 smaller">
<h2>Simple vs.&nbsp;multiple regression estimates</h2>
<p>Compare <span class="math inline">\tilde y = \tilde\beta_0 + \tilde\beta_1 x_1</span> with <span class="math inline">\hat y = \hat\beta_0 + \hat\beta_1 x_1 + \hat\beta_2 x_2</span>. In general <span class="math inline">\tilde\beta_1 \neq \hat\beta_1</span>, and in fact</p>
<p><span class="math display">
\tilde\beta_1 = \hat\beta_1 + \hat\beta_2\,\tilde\delta_1
</span></p>
<p>where <span class="math inline">\tilde\delta_1</span> is the slope from regressing <span class="math inline">x_2</span> on <span class="math inline">x_1</span>.</p>
<div class="fragment">
<div class="quiz" data-id="w4-same" data-answer="a,c">
<p><strong>When are the simple and the multiple regression estimates of the slope on <span class="math inline">x_1</span> equal? Select all that apply.</strong></p>
<p><span data-opt="a">A) When <span class="math inline">\hat\beta_2 = 0</span>: <span class="math inline">x_2</span> has no partial effect in the sample</span></p>
<p><span data-opt="b">B) When <span class="math inline">x_2</span> has a larger variance than <span class="math inline">x_1</span></span></p>
<p><span data-opt="c">C) When <span class="math inline">x_1</span> and <span class="math inline">x_2</span> are uncorrelated in the sample, so <span class="math inline">\tilde\delta_1 = 0</span></span></p>
<div class="explain">
<p>Both cases make the second term <span class="math inline">\hat\beta_2\tilde\delta_1</span> vanish. With gpa1: <span class="math inline">0.0271 = 0.0094 + 0.453 \times 0.039</span>.</p>
</div>
</div>
</div>
</section>
<section id="where-that-identity-comes-from" class="slide level2 smaller">
<h2>Where that identity comes from</h2>
<p>The simple regression slope is <span class="math inline">\;\tilde\beta_1 = \dfrac{\sum_i (x_{i1}-\bar x_1)\,y_i}{\sum_i (x_{i1}-\bar x_1)^2}</span>. Write <span class="math inline">y_i</span> with the <strong>multiple</strong> regression fit, <span class="math inline">y_i = \hat\beta_0 + \hat\beta_1x_{i1} + \hat\beta_2x_{i2} + \hat u_i</span>:</p>
<p><span class="math display">
\tilde\beta_1 = \frac{\sum_i (x_{i1}-\bar x_1)\big(\hat\beta_0 + \hat\beta_1 x_{i1} + \hat\beta_2 x_{i2} + \hat u_i\big)}{\sum_i (x_{i1}-\bar x_1)^2}
</span></p>
<div class="fragment">
<p>Three OLS algebra facts do the work: <span class="math inline">\sum_i(x_{i1}-\bar x_1) = 0</span> kills the intercept, <span class="math inline">\sum_i (x_{i1}-\bar x_1)\hat u_i = 0</span> kills the residual term, and the <span class="math inline">\hat\beta_1</span> term leaves exactly <span class="math inline">\hat\beta_1</span>. What survives is</p>
<p><span class="math display">
\tilde\beta_1 = \hat\beta_1 + \hat\beta_2\,\underbrace{\frac{\sum_i (x_{i1}-\bar x_1)x_{i2}}{\sum_i (x_{i1}-\bar x_1)^2}}_{\tilde\delta_1\;=\;\text{slope of } x_2 \text{ on } x_1}
</span></p>
<p>This is a <strong>sample</strong> identity — no assumptions yet. Take expectations and the same algebra gives the <strong>omitted variable bias</strong> formula on the next slides.</p>
</div>
</section>
<section id="goodness-of-fit" class="slide level2 smaller">
<h2>Goodness of fit</h2>
<p>The same definitions as before: <span class="math inline">SST = SSE + SSR</span> and</p>
<p><span class="math display">
R^2 = \frac{SSE}{SST} = 1 - \frac{SSR}{SST} = \big[\text{Corr}(y, \hat y)\big]^2
</span></p>
<p><span class="math inline">R^2</span> is the share of the sample variation in <span class="math inline">y</span> explained <strong>jointly</strong> by <span class="math inline">x_1, \dots, x_k</span>. For gpa1: <span class="math inline">R^2 = 0.176</span>.</p>
<div class="fragment">
<div title="R² never decreases when you add a regressor">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>R² never decreases when you add a regressor</strong></p>
</div>
<div class="callout-content">
<p>Adding a variable can only lower the SSR (or leave it unchanged), so <span class="math inline">R^2</span> goes up, <strong>even if the new variable is pure noise</strong>. So <span class="math inline">R^2</span> alone is a poor guide for choosing regressors. We will use the <strong>adjusted <span class="math inline">R^2</span></strong> and <span class="math inline">F</span> tests later.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Regression through the origin</strong> (<span class="math inline">\tilde y = \tilde\beta_1 x_1 + \dots + \tilde\beta_k x_k</span>): <span class="math inline">R^2</span> can be negative, and the estimators are biased if the true intercept is not zero.</p>
</div>
</section></section>
<section>
<section id="statistical-properties" class="title-slide slide level1 section-slide center">
<h1>Statistical properties</h1>
<p>MLR.1–MLR.4 and unbiasedness, irrelevant variables, and <strong>omitted variable bias</strong>.</p>
</section>
<section id="assumptions-mlr.1mlr.4" class="slide level2 smaller">
<h2>Assumptions MLR.1–MLR.4</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">MLR.1 · Linear in parameters</span></p>
<p><span class="math inline">y = \beta_0 + \beta_1 x_1 + \dots + \beta_k x_k + u</span></p>
</div>
<div class="card">
<p><span class="ct">MLR.2 · Random sampling</span></p>
<p><span class="math inline">\{(x_{i1},\dots,x_{ik},y_i): i=1,\dots,n\}</span> is a random sample.</p>
</div>
</div><div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">MLR.3 · No perfect collinearity</span></p>
<p>No <span class="math inline">x</span> is constant, and no <strong>exact linear</strong> relationship holds among the <span class="math inline">x</span>’s. They <strong>may be correlated</strong>, just not perfectly.</p>
</div>
<div class="card">
<p><span class="ct">MLR.4 · Zero conditional mean</span></p>
<p><span class="math inline">E(u \mid x_1, \dots, x_k) = 0</span>. It fails with a wrong functional form, omitted variables correlated with the <span class="math inline">x</span>’s, or measurement error.</p>
</div>
</div></div>
<div title="Theorem 3.1: unbiasedness of OLS">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Theorem 3.1: unbiasedness of OLS</strong></p>
</div>
<div class="callout-content">
<p>Under MLR.1–MLR.4, <span class="math inline">\;E(\hat\beta_j) = \beta_j</span> for <span class="math inline">j = 0, 1, \dots, k</span>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="your-turn-perfect-collinearity" class="slide level2 smaller">
<h2>Your turn: perfect collinearity?</h2>
<div class="sorter" data-id="w4-sort-collin">
<div class="bins">
<div class="bin" data-bin="ok">
<p>Allowed (MLR.3 holds)</p>
</div>
<div class="bin" data-bin="perf">
<p>Perfect collinearity (MLR.3 fails)</p>
</div>
</div>
<div class="items">
<p><span class="item" data-bin="ok"><span class="math inline">inc</span> and <span class="math inline">inc^2</span> in the same model</span> <span class="item" data-bin="perf">income in dollars <strong>and</strong> income in thousands of dollars</span> <span class="item" data-bin="perf"><span class="math inline">\log(inc)</span> and <span class="math inline">\log(inc^2)</span></span> <span class="item" data-bin="ok"><span class="math inline">educ</span> and <span class="math inline">exper</span>, which are correlated</span> <span class="item" data-bin="perf">shares of spending on food, housing and other, which sum to 1, plus an intercept</span> <span class="item" data-bin="ok"><span class="math inline">expend</span> and <span class="math inline">avginc</span> with correlation 0.9</span></p>
</div>
</div>
<div class="tiny muted">
<p>Hint: <span class="math inline">\log(inc^2) = 2\log(inc)</span>. And <span class="math inline">inc^2</span> is a <strong>nonlinear</strong> function of <span class="math inline">inc</span>.</p>
</div>
</section>
<section id="including-an-irrelevant-variable" class="slide level2 smaller">
<h2>Including an irrelevant variable</h2>
<p>Suppose the true model is <span class="math inline">y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + u</span>, but we also include <span class="math inline">x_3</span> with <span class="math inline">\beta_3 = 0</span> (<strong>overspecification</strong>).</p>
<ul>
<li>All estimators remain <strong>unbiased</strong>: <span class="math inline">E(\hat\beta_1)=\beta_1</span>, <span class="math inline">E(\hat\beta_2)=\beta_2</span> and <span class="math inline">E(\hat\beta_3)=0</span>.</li>
<li><strong>But</strong> the variances of the other estimators can <strong>increase</strong> (see multicollinearity below).</li>
</ul>
<div class="fragment">
<div title="Omitting a relevant variable is worse">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Omitting a relevant variable is worse</strong></p>
</div>
<div class="callout-content">
<p>Leaving out a variable whose coefficient is <strong>not</strong> zero (<strong>underspecification</strong>) generally makes OLS <strong>biased</strong>.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="omitted-variable-bias-the-formula" class="slide level2 smaller">
<h2>Omitted variable bias: the formula</h2>
<p>True model: <span class="math inline">y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + u</span>. We omit <span class="math inline">x_2</span> and estimate <span class="math inline">\tilde y = \tilde\beta_0 + \tilde\beta_1 x_1</span>.</p>
<div class="fragment">
<p>Using <span class="math inline">\tilde\beta_1 = \hat\beta_1 + \hat\beta_2\tilde\delta_1</span> and taking expectations:</p>
<p><span class="math display">
E(\tilde\beta_1) = \beta_1 + \beta_2\,\tilde\delta_1
\qquad\Longrightarrow\qquad
\text{Bias}(\tilde\beta_1) = \beta_2\,\tilde\delta_1
</span></p>
<p>where <span class="math inline">\tilde\delta_1</span> is the slope from regressing <span class="math inline">x_2</span> on <span class="math inline">x_1</span>.</p>
</div>
<div class="fragment">
<div class="columns">
<div class="column" style="width:55%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\text{Corr}(x_1,x_2) &gt; 0</span></th>
<th style="text-align: center;"><span class="math inline">\text{Corr}(x_1,x_2) &lt; 0</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\beta_2 &gt; 0</span></td>
<td style="text-align: center;"><strong>positive</strong> bias</td>
<td style="text-align: center;">negative bias</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\beta_2 &lt; 0</span></td>
<td style="text-align: center;">negative bias</td>
<td style="text-align: center;"><strong>positive</strong> bias</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<p>The bias is <strong>zero</strong> only if <span class="math inline">\beta_2 = 0</span> <strong>or</strong> <span class="math inline">x_1</span> and <span class="math inline">x_2</span> are uncorrelated.</p>
</div></div>
</div>
</section>
<section id="interactive-omitted-variable-bias" class="slide level2 smaller">
<h2>Interactive: omitted variable bias</h2>
<div class="widget" data-widget="ovb">

</div>
</section>
<section id="example-ability-bias-in-the-wage-equation" class="slide level2 smaller">
<h2>Example: ability bias in the wage equation</h2>
<p><span class="math display">
wage = \beta_0 + \beta_1 educ + \beta_2 abil + u
</span></p>
<p>Ability is <strong>unobserved</strong>, so we estimate <span class="math inline">wage = \beta_0 + \beta_1 educ + v</span> with <span class="math inline">v = \beta_2 abil + u</span>.</p>
<div class="quiz" data-id="w4-ability" data-answer="a">
<p><strong>What is the likely direction of the bias in <span class="math inline">\tilde\beta_1</span>?</strong></p>
<p><span data-opt="a">A) Upward: <span class="math inline">\beta_2 &gt; 0</span> and ability is positively correlated with education</span></p>
<p><span data-opt="b">B) Downward: ability lowers wages</span></p>
<p><span data-opt="c">C) No bias, because ability is unobserved</span></p>
<div class="explain">
<p>More able people earn more (<span class="math inline">\beta_2&gt;0</span>) and tend to get more schooling (<span class="math inline">\text{Corr}&gt;0</span>). The simple regression <strong>overstates</strong> the return to education: part of the ability effect is attributed to education. Being unobserved is exactly what causes the problem.</p>
</div>
</div>
<aside class="notes">
<p>More than two regressors: if the omitted x3 is correlated with x1 only, all the estimated slopes are generally biased, unless x1 and x2 are uncorrelated.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-variance-of-ols" class="title-slide slide level1 section-slide center">
<h1>The variance of OLS</h1>
<p>MLR.5, multicollinearity, standard errors and the <strong>Gauss–Markov</strong> theorem.</p>
</section>
<section id="mlr.5-and-the-gaussmarkov-assumptions" class="slide level2 smaller">
<h2>MLR.5 and the Gauss–Markov assumptions</h2>
<p><strong>MLR.5 · Homoskedasticity:</strong> <span class="math inline">\;\text{Var}(u \mid x_1, \dots, x_k) = \sigma^2</span></p>
<p>MLR.1–MLR.5 together are the <strong>Gauss–Markov assumptions</strong> for cross-sectional data. MLR.4 and MLR.5 can be written as</p>
<p><span class="math display">
E(y\mid \mathbf x) = \beta_0 + \beta_1 x_1 + \dots + \beta_k x_k, \qquad \text{Var}(y\mid \mathbf x) = \sigma^2
</span></p>
<div class="fragment">
<div title="Theorem 3.2: sampling variances of the OLS slopes">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Theorem 3.2: sampling variances of the OLS slopes</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">
\text{Var}(\hat\beta_j) = \frac{\sigma^2}{SST_j\,(1 - R_j^2)}, \qquad j = 1,\dots,k
</span></p>
<p><span class="math inline">SST_j = \sum_i (x_{ij} - \bar x_j)^2</span> is the total variation in <span class="math inline">x_j</span>, and <span class="math inline">R_j^2</span> is the <span class="math inline">R^2</span> from regressing <span class="math inline">x_j</span> on <strong>all other</strong> regressors.</p>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>Three drivers: the error variance <span class="math inline">\sigma^2</span> (↑ var), the variation in <span class="math inline">x_j</span> (↓ var), and <strong>how well the other <span class="math inline">x</span>’s explain <span class="math inline">x_j</span></strong> (<span class="math inline">R_j^2</span> ↑ var).</p>
</div>
</section>
<section id="multicollinearity-the-intuition" class="slide level2 smaller">
<h2>Multicollinearity: the intuition</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>A firm always runs <strong>TV</strong> and <strong>radio</strong> ads in the same weeks. Sales rise in those weeks.</p>
<ul>
<li>Was it the TV ads or the radio ads? The data <strong>never</strong> show one without the other.</li>
<li>To separate the two effects we need weeks where one changes <strong>and the other does not</strong>.</li>
<li>The fewer such weeks, the less information we have, and the <strong>noisier</strong> the estimates.</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="card">
<p><span class="ct">Link to the formula</span></p>
<p>By partialling out, <span class="math inline">\hat\beta_1</span> uses only <span class="math inline">\hat r_{i1}</span>, the part of <span class="math inline">x_1</span> <strong>not explained</strong> by the other regressors. Its total variation is</p>
<p><span class="math display">\textstyle\sum_i \hat r_{i1}^2 = SST_1\,(1-R_1^2)</span></p>
<p>and this is the denominator of <span class="math inline">\text{Var}(\hat\beta_1)</span>.</p>
</div>
</div></div>
<div title="Variance inflation factor">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Variance inflation factor</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">VIF_1 = 1/(1-R_1^2)</span>: how many times larger <span class="math inline">\text{Var}(\hat\beta_1)</span> is than it would be if <span class="math inline">x_1</span> were uncorrelated with the other regressors. A common rule of thumb flags <span class="math inline">VIF &gt; 10</span>, but there is no strict cutoff.</p>
</div>
</div>
</div>
</div>
</section>
<section id="interactive-multicollinearity" class="slide level2 smaller">
<h2>Interactive: multicollinearity</h2>
<div class="widget" data-widget="mcoll">

</div>
<aside class="notes">
<p>Suggested sequence: start at 0, then 0.5, 0.9, 0.99 and finally 1. Point to the red lines in the left panel: they are the only variation that identifies beta1. At 0.99 about 2% of the information is left and the variance is about 50 times larger. The right panel shows the negative correlation of the estimates: the data pin down beta1 + beta2 well, but not the split. At 1 there is perfect collinearity (MLR.3 fails). Also stress that multicollinearity does not cause bias.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="estimating-sigma2-and-standard-errors" class="slide level2 smaller">
<h2>Estimating <span class="math inline">\sigma^2</span> and standard errors</h2>
<p><span class="math display">
\hat\sigma^2 = \frac{\sum_i \hat u_i^2}{n - k - 1} = \frac{SSR}{n - k - 1}, \qquad
\text{se}(\hat\beta_j) = \frac{\hat\sigma}{\sqrt{SST_j\,(1 - R_j^2)}}
</span></p>
<ul>
<li><strong>Degrees of freedom:</strong> <span class="math inline">n - (k+1)</span> = observations − estimated parameters. The <span class="math inline">k+1</span> first-order conditions put <span class="math inline">k+1</span> restrictions on the residuals.</li>
<li><span class="math inline">\hat\sigma</span> is the <strong>standard error of the regression</strong> (SER). It can rise or fall when a variable is added.</li>
</ul>
</section>
<section id="standard-errors-in-r-and-in-equation-form" class="slide level2 smaller">
<h2>Standard errors in R, and in equation form</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(colGPA <span class="sc">~</span> hsGPA <span class="sc">+</span> ACT, <span class="at">data =</span> gpa1)</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(g1)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                Estimate Std. Error   t value     Pr(&gt;|t|)
#&gt; (Intercept) 1.286327767 0.34082212 3.7741910 2.375872e-04
#&gt; hsGPA       0.453455885 0.09581292 4.7327219 5.421580e-06
#&gt; ACT         0.009426012 0.01077719 0.8746263 3.832969e-01</code></pre>
</div>
</div>
<p>The same result, written the way papers report it — <strong>standard errors in parentheses under the estimates</strong>:</p>
<p><span class="math display">
\begin{aligned} \widehat{colGPA} &amp;=  \underset{\small (0.341)}{1.29} + \underset{\small (0.0958)}{0.453}\,hsGPA + \underset{\small (0.0108)}{0.00943}\,ACT \\ &amp; n = 141,\quad R^2 = 0.176 \end{aligned}
</span></p>
</section>
<section id="the-gaussmarkov-theorem" class="slide level2 smaller">
<h2>The Gauss–Markov theorem</h2>
<div title="Theorem 3.4 (Gauss–Markov)">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Theorem 3.4 (Gauss–Markov)</strong></p>
</div>
<div class="callout-content">
<p>Under <strong>MLR.1–MLR.5</strong>, the OLS estimators <span class="math inline">\hat\beta_0, \hat\beta_1, \dots, \hat\beta_k</span> are the <strong>best linear unbiased estimators (BLUE)</strong> of <span class="math inline">\beta_0, \beta_1, \dots, \beta_k</span>.</p>
</div>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong>B</strong>est: smallest variance</li>
<li><strong>L</strong>inear: <span class="math inline">\tilde\beta_j = \sum_i w_{ij}\, y_i</span>, where the weights may depend on the <span class="math inline">x</span>’s. OLS has <span class="math inline">w_{ij} = \hat r_{ij}/\sum_i \hat r_{ij}^2</span>.</li>
<li><strong>U</strong>nbiased: <span class="math inline">E(\tilde\beta_j) = \beta_j</span></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Why it matters:</strong> if the assumptions hold, there is no need to look for another linear unbiased estimator.</p>
<ul>
<li>If <strong>MLR.4</strong> fails, OLS is <strong>biased</strong>.</li>
<li>If <strong>MLR.5</strong> fails, OLS is still unbiased but <strong>no longer “best”</strong> (Week 12).</li>
</ul>
</div></div>
</section>
<section id="check-your-understanding" class="slide level2 smaller">
<h2>Check your understanding</h2>
<div class="quiz" data-id="w4-gm" data-answer="c">
<p><strong>A researcher adds a variable that is highly correlated with <span class="math inline">x_1</span> but has no effect on <span class="math inline">y</span>. What happens to <span class="math inline">\hat\beta_1</span>?</strong></p>
<p><span data-opt="a">A) It becomes biased</span></p>
<p><span data-opt="b">B) Nothing at all</span></p>
<p><span data-opt="c">C) It stays unbiased, but its variance increases because <span class="math inline">R_1^2</span> goes up</span></p>
<p><span data-opt="d">D) Its variance decreases because the model has more information</span></p>
<div class="explain">
<p>An irrelevant variable does not cause bias, but it raises <span class="math inline">R_1^2</span> and so <span class="math inline">\text{Var}(\hat\beta_1) = \sigma^2/[SST_1(1-R_1^2)]</span>. There is a <strong>trade-off</strong>: omitting a relevant variable causes bias, while including an irrelevant one costs precision.</p>
</div>
</div>
</section>
<section id="r-toolkit-for-this-topic" class="slide level2 smaller">
<h2>R toolkit for this topic</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">lm</span>(colGPA <span class="sc">~</span> hsGPA <span class="sc">+</span> ACT, <span class="at">data =</span> gpa1)   <span class="co"># multiple regression</span></span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res)                                      <span class="co"># estimates, se, R^2</span></span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># partialling out: the same coefficient on hsGPA</span></span>
<span id="cb5-5"><a aria-hidden="true" tabindex="-1"></a>r1 <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(hsGPA <span class="sc">~</span> ACT, <span class="at">data =</span> gpa1))</span>
<span id="cb5-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(gpa1<span class="sc">$</span>colGPA <span class="sc">~</span> r1))</span>
<span id="cb5-7"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a aria-hidden="true" tabindex="-1"></a><span class="co"># omitted variable bias identity: beta_tilde = beta_hat + beta2_hat * delta</span></span>
<span id="cb5-9"><a aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">lm</span>(ACT <span class="sc">~</span> hsGPA, <span class="at">data =</span> gpa1))[<span class="dv">2</span>]</span>
<span id="cb5-10"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(res)[<span class="st">"hsGPA"</span>] <span class="sc">+</span> <span class="fu">coef</span>(res)[<span class="st">"ACT"</span>] <span class="sc">*</span> delta     <span class="co"># = simple slope on hsGPA</span></span>
<span id="cb5-11"><a aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(res)                                     <span class="co"># variance inflation factors</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key takeaways</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ol type="1">
<li>Multiple regression holds other observed factors <strong>fixed explicitly</strong>.</li>
<li><span class="math inline">\hat\beta_j</span> is the effect of <span class="math inline">x_j</span> after <strong>partialling out</strong> the other <span class="math inline">x</span>’s.</li>
<li>Under <strong>MLR.1–MLR.4</strong>, OLS is unbiased. MLR.3 rules out only <strong>perfect</strong> collinearity.</li>
<li><strong>Omitted variable bias</strong> <span class="math inline">= \beta_2\tilde\delta_1</span>. Its sign follows from the <span class="math inline">2\times 2</span> table.</li>
<li><span class="math inline">\text{Var}(\hat\beta_j) = \sigma^2/[SST_j(1-R_j^2)]</span>. Multicollinearity inflates it.</li>
<li>Under <strong>MLR.1–MLR.5</strong>, OLS is <strong>BLUE</strong> (Gauss–Markov).</li>
</ol>
</div><div class="column" style="width:40%;">
<div class="card">
<p><span class="ct">Next topic</span></p>
<p><strong>Multiple regression II</strong>: sampling distributions, <span class="math inline">t</span> tests and confidence intervals.</p>
<p><span class="tag">Wooldridge ch.&nbsp;4</span> <span class="tag">Heiss ch.&nbsp;4</span></p>
</div>
<div class="score-box">

</div>
</div></div>
<script src="assets/deck04.js"></script>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Econometrics I · Yıldız Technical University</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"numbers":true},
'chalkboard': {"buttons":true,"theme":"whiteboard","boardmarkerWidth":3},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 760,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>