<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan">
  <title>Econometrics I – Multiple Regression Analysis II</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-70fcdf68ba588c6f83f9e4af10fa12ef.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- shared interactive layer for all Econometrics I decks -->
  <script src="assets/wooldridge-data.js"></script>
  <script src="assets/hmda-data.js"></script>
  <script src="assets/econ-core.js"></script>
  <script src="assets/econ-ui.js"></script>
  <script src="assets/widgets-shared.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Multiple Regression Analysis II</h1>
  <p class="subtitle">Topic 5 · Inference: t tests, p-values and confidence intervals</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan 
</div>
        <p class="quarto-title-affiliation">
            Yıldız Technical University · Department of Economics
          </p>
    </div>
</div>

  <p class="date">Fall 2026</p>
</section>
<section id="todays-roadmap" class="slide level2">
<h2>Today’s roadmap</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="objectives">
<p><strong>By the end of this lecture you should be able to</strong></p>
<ul>
<li>state the <strong>normality</strong> assumption (MLR.6) and why we need it</li>
<li>carry out <strong>one-sided</strong> and <strong>two-sided</strong> <span class="math inline">t</span> tests, including <span class="math inline">H_0: \beta_j = a_j</span></li>
<li>compute and interpret <strong>p-values</strong></li>
<li>construct and interpret <strong>confidence intervals</strong></li>
<li>read a regression <strong>output</strong> line by line</li>
</ul>
</div>
</div><div class="column" style="width:45%;">
<div class="card">
<p><span class="ct">Reading</span></p>
<p><span class="tag weektag">Fall 2026 · Week 5</span></p>
<p><span class="tag">Wooldridge ch.&nbsp;4.1–4.3</span> <span class="tag">Heiss ch.&nbsp;4</span> <span class="tag">Stock &amp; Watson ch.&nbsp;7</span></p>
</div>
<div class="card">
<p><span class="ct">Lab</span></p>
<p>Hypothesis tests in R. See <em>Lab 06</em> on the course page.</p>
</div>
<div class="card">
<p><span class="ct">Last week</span></p>
<p>OLS is unbiased and BLUE, with standard errors <span class="math inline">\text{se}(\hat\beta_j)</span>.</p>
</div>
</div></div>
</section>
<section id="warm-up-could-it-be-zero" class="slide level2">
<h2>Warm-up: could it be zero?</h2>
<p>In the <code>wage1</code> regression of <span class="math inline">\log(wage)</span> on <span class="math inline">educ</span>, <span class="math inline">exper</span> and <span class="math inline">tenure</span>, the coefficient on experience is</p>
<p><span class="math display">
\hat\beta_{exper} = 0.0041, \qquad \text{se}(\hat\beta_{exper}) = 0.0017
</span></p>
<div class="quiz" data-id="w5-warmup" data-answer="c">
<p><strong>Could the true effect of experience be zero, and we just got an unlucky sample?</strong></p>
<p><span data-opt="a">A) No, the estimate is positive, so the true effect must be positive</span></p>
<p><span data-opt="b">B) Yes, and there is no way to judge how likely that is</span></p>
<p><span data-opt="c">C) It is possible, but the estimate is about 2.4 standard errors away from 0, which would be unusual if the true effect were zero</span></p>
<div class="explain">
<p>Estimates vary from sample to sample, so a positive estimate does not prove a positive effect. But we can measure the distance from zero <strong>in standard errors</strong>: <span class="math inline">0.0041/0.0017 \approx 2.4</span>. Today we turn this idea into a formal <strong><span class="math inline">t</span> test</strong> with a known probability of error.</p>
</div>
</div>
</section>
<section>
<section id="sampling-distributions" class="title-slide slide level1 section-slide center">
<h1>Sampling distributions</h1>
<p>One more assumption (normality) turns the estimates into a distribution we can test with.</p>
</section>
<section id="assumption-mlr.6-normality" class="slide level2 smaller">
<h2>Assumption MLR.6: normality</h2>
<p>To test hypotheses we need the <strong>full sampling distribution</strong> of <span class="math inline">\hat\beta_j</span>, not only its mean and variance.</p>
<div title="MLR.6 · Normality">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>MLR.6 · Normality</strong></p>
</div>
<div class="callout-content">
<p>The population error <span class="math inline">u</span> is <strong>independent</strong> of <span class="math inline">x_1, \dots, x_k</span> and normally distributed: <span class="math inline">\;u \sim \text{Normal}(0, \sigma^2)</span>.</p>
</div>
</div>
</div>
</div>
<ul>
<li>MLR.6 is stronger than MLR.4 and MLR.5: it implies both.</li>
<li><strong>MLR.1–MLR.6</strong> are the <strong>classical linear model (CLM)</strong> assumptions. Under them, OLS is the minimum-variance unbiased estimator among <strong>all</strong> estimators, not only linear ones.</li>
<li>Compactly: <span class="math inline">\;y \mid \mathbf x \sim \text{Normal}(\beta_0 + \beta_1 x_1 + \dots + \beta_k x_k,\; \sigma^2)</span></li>
</ul>
</section>
<section id="is-normality-reasonable" class="slide level2 smaller">
<h2>Is normality reasonable?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">Argument for</span></p>
<p><span class="math inline">u</span> is the <strong>sum of many</strong> unobserved factors. By the <strong>central limit theorem</strong>, a sum of many independent factors is approximately normal.</p>
</div>
</div><div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">Arguments against</span></p>
<ul>
<li>The factors may not enter <strong>additively</strong>.</li>
<li>Some variables cannot be normal: wages are <strong>positive and skewed</strong>, and minimum wage laws pile up observations.</li>
</ul>
</div>
</div></div>
<div class="fragment">
<ul>
<li>Normality is an <strong>empirical</strong> question. A transformation such as <span class="math inline">\log(wage)</span> often makes the distribution much closer to normal.</li>
<li>In <strong>large samples</strong> we can drop MLR.6 altogether: the <span class="math inline">t</span> statistic is then approximately normal anyway (Week 6).</li>
</ul>
</div>
</section>
<section id="sampling-distributions-of-the-ols-estimators" class="slide level2 smaller">
<h2>Sampling distributions of the OLS estimators</h2>
<div title="Theorem 4.1: normal sampling distributions">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Theorem 4.1: normal sampling distributions</strong></p>
</div>
<div class="callout-content">
<p>Under MLR.1–MLR.6, conditional on the <span class="math inline">x</span>’s:</p>
<p><span class="math display">
\hat\beta_j \sim \text{Normal}\big(\beta_j,\; \text{Var}(\hat\beta_j)\big) \qquad\Rightarrow\qquad \frac{\hat\beta_j - \beta_j}{\text{sd}(\hat\beta_j)} \sim \text{Normal}(0,1)
</span></p>
</div>
</div>
</div>
</div>
<p>Why: <span class="math inline">\hat\beta_j</span> is a <strong>linear combination of the errors</strong>, and linear combinations of normal variables are normal.</p>
<div class="fragment">
<div title="Theorem 4.2: the t distribution">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Theorem 4.2: the t distribution</strong></p>
</div>
<div class="callout-content">
<p>Replacing the unknown sd by the estimated <strong>se</strong>:</p>
<p><span class="math display">
\frac{\hat\beta_j - \beta_j}{\text{se}(\hat\beta_j)} \sim t_{n-k-1}
</span></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>The t distribution has fatter tails than the normal because sigma-hat is itself estimated. As n-k-1 grows it approaches the standard normal. Show this in the t explorer by switching on N(0,1) and lowering df.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="testing-a-single-parameter-the-t-test" class="title-slide slide level1 section-slide center">
<h1>Testing a single parameter: the <em>t</em> test</h1>
<p>A five-step recipe, then right-tail, left-tail and two-sided examples, p-values and significance.</p>
</section>
<section id="the-recipe" class="slide level2 smaller">
<h2>The recipe</h2>
<div class="flow">
<div class="step">
<p><span class="n">1</span> <strong>Hypotheses</strong> <span class="math inline">H_0: \beta_j = a_j</span> and an alternative <span class="math inline">H_1</span></p>
</div>
<div class="step">
<p><span class="n">2</span> <strong>Significance level</strong> <span class="math inline">\alpha</span> = P(reject <span class="math inline">H_0</span> when it is true), e.g.&nbsp;5%</p>
</div>
<div class="step">
<p><span class="n">3</span> <strong>Test statistic</strong> <span class="math inline">t = (\hat\beta_j - a_j)/\text{se}(\hat\beta_j)</span></p>
</div>
<div class="step">
<p><span class="n">4</span> <strong>Critical value</strong> <span class="math inline">c</span> from <span class="math inline">t_{n-k-1}</span> for the chosen <span class="math inline">\alpha</span></p>
</div>
<div class="step">
<p><span class="n">5</span> <strong>Decision</strong> Reject <span class="math inline">H_0</span> if <span class="math inline">t</span> falls in the rejection region</p>
</div>
</div>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Alternative</th>
<th style="text-align: left;">Rejection rule</th>
<th style="text-align: center;"><span class="math inline">c</span> at 5%, large df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">H_1: \beta_j &gt; a_j</span> (right tail)</td>
<td style="text-align: left;"><span class="math inline">t &gt; c</span></td>
<td style="text-align: center;">1.645</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">H_1: \beta_j &lt; a_j</span> (left tail)</td>
<td style="text-align: left;"><span class="math inline">t &lt; -c</span></td>
<td style="text-align: center;">1.645</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">H_1: \beta_j \neq a_j</span> (two-sided)</td>
<td style="text-align: left;"><span class="math inline">\lvert t\rvert &gt; c</span></td>
<td style="text-align: center;">1.96</td>
</tr>
</tbody>
</table>
<div title="Remember">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Remember</strong></p>
</div>
<div class="callout-content">
<p>Hypotheses are statements about the <strong>population</strong> parameters <span class="math inline">\beta_j</span>, never about the estimates <span class="math inline">\hat\beta_j</span>.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="right-tail-test-from-r-output-to-equation" class="slide level2 smaller">
<h2>Right-tail test: from R output to equation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ <span class="sc">+</span> exper <span class="sc">+</span> tenure, <span class="at">data =</span> wage1)</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(res)<span class="sc">$</span>coefficients, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;             Estimate Std. Error  t value Pr(&gt;|t|)
#&gt; (Intercept)  0.28436    0.10419  2.72923  0.00656
#&gt; educ         0.09203    0.00733 12.55525  0.00000
#&gt; exper        0.00412    0.00172  2.39144  0.01714
#&gt; tenure       0.02207    0.00309  7.13307  0.00000</code></pre>
</div>
</div>
<div class="fragment">
<p>The same results in <strong>equation form</strong>, with standard errors <strong>in parentheses under the estimates</strong>:</p>
<p><span class="math display">
\begin{aligned} \widehat{\log(wage)} &amp;=  \underset{\small (0.104)}{0.284} + \underset{\small (0.00733)}{0.0920}\,educ + \underset{\small (0.00172)}{0.00412}\,exper + \underset{\small (0.00309)}{0.0221}\,tenure \\ &amp; n = 526,\quad R^2 = 0.316 \end{aligned}
</span></p>
<div class="tiny muted">
<p><strong>Estimate</strong> column → the coefficients. <strong>Std. Error</strong> column → the numbers in parentheses. This is how results are reported in papers and in exams.</p>
</div>
</div>
</section>
<section id="right-tail-test-the-return-to-experience" class="slide level2 smaller">
<h2>Right-tail test: the return to experience</h2>
<p><span class="math display">
\begin{aligned} \widehat{\log(wage)} &amp;=  \underset{\small (0.104)}{0.284} + \underset{\small (0.00733)}{0.0920}\,educ + \underset{\small (0.00172)}{0.00412}\,exper + \underset{\small (0.00309)}{0.0221}\,tenure \\ &amp; n = 526,\quad R^2 = 0.316 \end{aligned}
</span></p>
<p><span class="math inline">H_0: \beta_{exper} = 0\;</span> vs.&nbsp;<span class="math inline">\;H_1: \beta_{exper} &gt; 0</span>, <span class="math inline">\quad</span> df <span class="math inline">= n - k - 1 = 526 - 3 - 1 = 522</span></p>
<div class="fragment">
<p><span class="math display">
t_{exper} = \frac{\hat\beta_{exper}}{\text{se}(\hat\beta_{exper})} = \frac{0.00412}{0.00172} = 2.39
</span></p>
</div>
<div class="fragment">
<p>One-sided critical values from <span class="math inline">t_{522}</span>: <span class="math inline">\;c_{0.05} = 1.648,\;\; c_{0.01} = 2.334</span></p>
<p><span class="math inline">2.39 &gt; 2.334</span>: <strong>reject <span class="math inline">H_0</span> at the 1% level.</strong> Holding education and tenure fixed, experience has a statistically significant positive effect on wages. Economically, one more year of experience raises the wage by about <strong>0.4%</strong>.</p>
</div>
</section>
<section id="interactive-t-test-explorer" class="slide level2 smaller">
<h2>Interactive: <em>t</em> test explorer</h2>
<div class="widget" data-widget="t-explorer">

</div>
<aside class="notes">
<p>Load the examples one by one. exper: right tail, rejected at 5% and 1%. enroll: left tail, not rejected. skipped: two-sided, strongly rejected. crime: H0 elasticity = 1, rejected in favor of &gt; 1. nox: H0 = -1 two-sided, not rejected. Then move alpha across the p-value to show that the p-value is the smallest level at which H0 is rejected. Turn on N(0,1) and lower df to show the fatter tails of the t distribution.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="left-tail-test-school-size-and-performance" class="slide level2 smaller">
<h2>Left-tail test: school size and performance</h2>
<p><code>meap93</code>: math pass rate <code>math10</code> (%) on teacher compensation <code>totcomp</code>, staff per 1,000 students <code>staff</code> and enrollment <code>enroll</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"meap93"</span>)</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math10 <span class="sc">~</span> totcomp <span class="sc">+</span> staff <span class="sc">+</span> enroll, <span class="at">data =</span> meap93)</span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m1)<span class="sc">$</span>coefficients, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;             Estimate Std. Error  t value Pr(&gt;|t|)
#&gt; (Intercept)  2.27402    6.11379  0.37195  0.71013
#&gt; totcomp      0.00046    0.00010  4.57003  0.00001
#&gt; staff        0.04792    0.03981  1.20359  0.22945
#&gt; enroll      -0.00020    0.00022 -0.91793  0.35920</code></pre>
</div>
</div>
<p><span class="math display">
\begin{aligned} \widehat{math10} &amp;=  \underset{\small (6.11)}{2.27} + \underset{\small (0.000100)}{0.000459}\,totcomp + \underset{\small (0.0398)}{0.0479}\,staff - \underset{\small (0.000215)}{0.000198}\,enroll \\ &amp; n = 408,\quad R^2 = 0.0541 \end{aligned}
</span></p>
</section>
<section id="left-tail-test-carrying-out-the-test" class="slide level2 smaller">
<h2>Left-tail test: carrying out the test</h2>
<p><span class="math display">
\begin{aligned} \widehat{math10} &amp;=  \underset{\small (6.11)}{2.27} + \underset{\small (0.000100)}{0.000459}\,totcomp + \underset{\small (0.0398)}{0.0479}\,staff - \underset{\small (0.000215)}{0.000198}\,enroll \\ &amp; n = 408,\quad R^2 = 0.0541 \end{aligned}
</span></p>
<p>Do larger schools hurt performance? <span class="math inline">\;H_0: \beta_{enroll} = 0\;</span> vs.&nbsp;<span class="math inline">\;H_1: \beta_{enroll} &lt; 0</span>, <span class="math inline">\quad</span> df <span class="math inline">= 408 - 4 = 404</span></p>
<div class="fragment">
<p><span class="math display">
t_{enroll} = \frac{-0.000198}{0.000215} = -0.92 \;&gt;\; -c_{0.05} = -1.65
</span></p>
<p><strong>Fail to reject <span class="math inline">H_0</span> at 5%.</strong> There is no evidence that, holding teacher pay and staff fixed, school size affects the pass rate.</p>
<div title="Note the scale">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note the scale</strong></p>
</div>
<div class="callout-content">
<p>The coefficients on <code>totcomp</code> and <code>enroll</code> look tiny because these variables are measured in dollars and students. A change of one dollar or one student is small.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="left-tail-test-a-level-log-model" class="slide level2 smaller">
<h2>Left-tail test: a level-log model</h2>
<p>Maybe a <strong>percentage</strong> change in enrollment is more natural:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math10 <span class="sc">~</span> <span class="fu">log</span>(totcomp) <span class="sc">+</span> <span class="fu">log</span>(staff) <span class="sc">+</span> <span class="fu">log</span>(enroll), <span class="at">data =</span> meap93)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="math display">
\begin{aligned} \widehat{math10} &amp;= - \underset{\small (48.70)}{207.66} + \underset{\small (4.06)}{21.16}\,\log(totcomp) + \underset{\small (4.19)}{3.98}\,\log(staff) - \underset{\small (0.693)}{1.27}\,\log(enroll) \\ &amp; n = 408,\quad R^2 = 0.0654 \end{aligned}
</span></p>
<div class="fragment">
<p><span class="math display">
t_{\log(enroll)} = \frac{-1.27}{0.693} = -1.83 \;&lt;\; -c_{0.05} = -1.65
</span></p>
<p><strong>Reject <span class="math inline">H_0</span> at 5%</strong> in favor of <span class="math inline">\beta_{\log(enroll)} &lt; 0</span>. A 10% larger enrollment lowers the predicted pass rate by about <span class="math inline">1.27 \times 10/100 = 0.13</span> percentage points: statistically significant, but economically small.</p>
</div>
</section>
<section id="two-sided-test-skipping-classes" class="slide level2 smaller">
<h2>Two-sided test: skipping classes</h2>
<p><code>gpa1</code>: college GPA on high-school GPA, ACT score and <code>skipped</code>, the average number of lectures missed per week.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"gpa1"</span>)</span>
<span id="cb6-2"><a aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">lm</span>(colGPA <span class="sc">~</span> hsGPA <span class="sc">+</span> ACT <span class="sc">+</span> skipped, <span class="at">data =</span> gpa1)</span>
<span id="cb6-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(g)<span class="sc">$</span>coefficients, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;             Estimate Std. Error t value Pr(&gt;|t|)
#&gt; (Intercept)   1.3896     0.3316  4.1910   0.0000
#&gt; hsGPA         0.4118     0.0937  4.3963   0.0000
#&gt; ACT           0.0147     0.0106  1.3933   0.1658
#&gt; skipped      -0.0831     0.0260 -3.1968   0.0017</code></pre>
</div>
</div>
<p><span class="math display">
\begin{aligned} \widehat{colGPA} &amp;=  \underset{\small (0.332)}{1.39} + \underset{\small (0.0937)}{0.412}\,hsGPA + \underset{\small (0.0106)}{0.0147}\,ACT - \underset{\small (0.0260)}{0.0831}\,skipped \\ &amp; n = 141,\quad R^2 = 0.234 \end{aligned}
</span></p>
</section>
<section id="two-sided-test-which-variables-matter" class="slide level2 smaller">
<h2>Two-sided test: which variables matter?</h2>
<p><span class="math display">
\begin{aligned} \widehat{colGPA} &amp;=  \underset{\small (0.332)}{1.39} + \underset{\small (0.0937)}{0.412}\,hsGPA + \underset{\small (0.0106)}{0.0147}\,ACT - \underset{\small (0.0260)}{0.0831}\,skipped \end{aligned}
</span></p>
<p><span class="math inline">H_0: \beta_j = 0</span> vs.&nbsp;<span class="math inline">H_1: \beta_j \neq 0</span>, df <span class="math inline">= 137</span>: <span class="math inline">\;c_{0.05} = 1.98,\; c_{0.01} = 2.61</span>. <strong>Compute each <span class="math inline">t</span> from the equation</strong>, then sort:</p>
<div class="sorter" data-id="w5-sort-gpa">
<div class="bins">
<div class="bin" data-bin="1">
<p>Significant at 1%</p>
</div>
<div class="bin" data-bin="no">
<p>Not significant at 10%</p>
</div>
</div>
<div class="items">
<p><span class="item" data-bin="1">hsGPA</span> <span class="item" data-bin="no">ACT</span> <span class="item" data-bin="1">skipped</span></p>
</div>
</div>
<div class="reveal-box" data-label="Show the t statistics">
<p><span class="math inline">t_{hsGPA} = 0.412/0.0937 = 4.40</span>, <span class="math inline">\;t_{ACT} = 0.0147/0.0106 = 1.39</span>, <span class="math inline">\;t_{skipped} = -0.0831/0.0260 = -3.20</span></p>
</div>
</section>
<section id="testing-other-values-h_0-beta_j-a_j" class="slide level2 smaller">
<h2>Testing other values: <span class="math inline">H_0: \beta_j = a_j</span></h2>
<p><span class="math display">
t = \frac{\hat\beta_j - a_j}{\text{se}(\hat\beta_j)} = \frac{\text{estimate} - \text{hypothesized value}}{\text{standard error}}
</span></p>
<p><strong>Campus crime</strong> (<code>campus</code>, 97 universities): does crime rise <strong>more than proportionally</strong> with university size?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"campus"</span>)</span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a>cr <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(crime) <span class="sc">~</span> <span class="fu">log</span>(enroll), <span class="at">data =</span> campus)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="math display">
\begin{aligned} \widehat{\log(crime)} &amp;= - \underset{\small (1.03)}{6.63} + \underset{\small (0.110)}{1.27}\,\log(enroll) \\ &amp; n = 97,\quad R^2 = 0.585 \end{aligned}
</span></p>
<p><span class="math inline">H_0: \beta_1 = 1</span> vs.&nbsp;<span class="math inline">H_1: \beta_1 &gt; 1</span>: <span class="math inline">\quad t = \dfrac{1.27 - 1}{0.110} \approx 2.46 &gt; c_{0.05} = 1.66\;</span> → <strong>reject</strong> <span class="math inline">H_0</span>.</p>
</section>
<section id="testing-other-values-house-prices-and-pollution" class="slide level2 smaller">
<h2>Testing other values: house prices and pollution</h2>
<p><code>hprice2</code> (506 communities): is the elasticity of house prices with respect to air pollution (<code>nox</code>) equal to −1?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"hprice2"</span>)</span>
<span id="cb9-2"><a aria-hidden="true" tabindex="-1"></a>hp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(nox) <span class="sc">+</span> <span class="fu">log</span>(dist) <span class="sc">+</span> rooms <span class="sc">+</span> stratio, <span class="at">data =</span> hprice2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="math display">
\begin{aligned} \widehat{\log(price)} &amp;=  \underset{\small (0.318)}{11.08} - \underset{\small (0.117)}{0.954}\,\log(nox) - \underset{\small (0.0431)}{0.134}\,\log(dist) \\ &amp; + \underset{\small (0.0185)}{0.255}\,rooms - \underset{\small (0.00590)}{0.0525}\,stratio \\ &amp; n = 506,\quad R^2 = 0.584 \end{aligned}
</span></p>
<p><span class="math inline">H_0: \beta_{\log(nox)} = -1</span> vs.&nbsp;<span class="math inline">H_1: \beta_{\log(nox)} \neq -1</span>: <span class="math inline">\quad t = \dfrac{-0.954 - (-1)}{0.117} \approx 0.39 &lt; 1.96\;</span> → <strong>fail to reject</strong> <span class="math inline">H_0</span>.</p>
<div title="A common mistake">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>A common mistake</strong></p>
</div>
<div class="callout-content">
<p>The <span class="math inline">t</span> value printed by R always tests <span class="math inline">H_0: \beta_j = 0</span>. For any other <span class="math inline">a_j</span> you must compute <span class="math inline">t</span> yourself.</p>
</div>
</div>
</div>
</div>
</section>
<section id="p-values" class="slide level2 smaller">
<h2>p-values</h2>
<p>Instead of fixing <span class="math inline">\alpha</span> in advance, ask: <strong>what is the smallest significance level at which <span class="math inline">H_0</span> would be rejected?</strong></p>
<p><span class="math display">
\text{two-sided: } p = P\big(|T| &gt; |t|\big), \qquad T \sim t_{n-k-1}
</span></p>
<ul>
<li><strong>Small</strong> p-value = strong evidence against <span class="math inline">H_0</span>. Reject <span class="math inline">H_0</span> at level <span class="math inline">\alpha</span> <strong>iff</strong> <span class="math inline">p &lt; \alpha</span>.</li>
<li>R reports p-values for <strong>two-sided</strong> tests of <span class="math inline">H_0: \beta_j = 0</span>. For a one-sided test in the direction of the estimate, halve it.</li>
<li>The <span class="math inline">t</span> explorer shows the p-value as the <strong>orange tail area</strong> beyond <span class="math inline">t</span>.</li>
</ul>
</section>
<section id="check-what-a-p-value-is-and-is-not" class="slide level2">
<h2>Check: what a p-value is (and is not)</h2>
<div class="quiz" data-id="w5-pval" data-answer="b">
<p><strong>A two-sided test gives p = 0.03. Which statement is correct?</strong></p>
<p><span data-opt="a">A) There is a 3% probability that <span class="math inline">H_0</span> is true</span></p>
<p><span data-opt="b">B) If <span class="math inline">H_0</span> were true, a <span class="math inline">|t|</span> at least this large would occur in only 3% of samples</span></p>
<p><span data-opt="c">C) We reject <span class="math inline">H_0</span> at the 1% level</span></p>
<div class="explain">
<p>The p-value is computed <strong>assuming <span class="math inline">H_0</span> is true</strong>. It is not the probability that <span class="math inline">H_0</span> is true. With <span class="math inline">p = 0.03</span> we reject at 5% and 10%, but <strong>not</strong> at 1%.</p>
</div>
</div>
</section>
<section id="statistical-vs.-economic-significance" class="slide level2 smaller">
<h2>Statistical vs.&nbsp;economic significance</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong>Statistical significance</strong> depends on the <span class="math inline">t</span> statistic, that is, on the <strong>size of the estimate relative to its se</strong>.</li>
<li><strong>Economic (practical) significance</strong> depends on the <strong>size of the estimate</strong> itself.</li>
<li>In large samples, tiny effects can be statistically significant, so smaller <span class="math inline">\alpha</span> (1%) is appropriate.</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Guidelines</strong></p>
<ol type="1">
<li>Check statistical significance. If significant, discuss the <strong>magnitude</strong>.</li>
<li>If not significant, check whether the effect is large and the p-value moderate (e.g., 0.10–0.20).</li>
<li>“Wrong” signs with small <span class="math inline">t</span> can be ignored. A <strong>significant</strong> wrong sign signals a problem with the model or the data.</li>
</ol>
</div></div>
<div class="fragment">
<div title="Large standard errors">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Large standard errors</strong></p>
</div>
<div class="callout-content">
<p>Standard errors shrink roughly like <span class="math inline">1/\sqrt{n}</span>. High <strong>multicollinearity</strong> inflates them. Often the only remedy is more data.</p>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="confidence-intervals" class="title-slide slide level1 section-slide center">
<h1>Confidence intervals</h1>
<p>The same information as a test, reported as a range of plausible values.</p>
</section>
<section id="constructing-a-confidence-interval" class="slide level2 smaller">
<h2>Constructing a confidence interval</h2>
<p>Since <span class="math inline">(\hat\beta_j - \beta_j)/\text{se}(\hat\beta_j) \sim t_{n-k-1}</span>, a <span class="math inline">100(1-\alpha)\%</span> <strong>confidence interval</strong> is</p>
<p><span class="math display">
\hat\beta_j \pm c \cdot \text{se}(\hat\beta_j), \qquad c = \text{the } (1-\tfrac{\alpha}{2}) \text{ quantile of } t_{n-k-1}
</span></p>
<p>Three ingredients: the <strong>estimate</strong>, its <strong>standard error</strong> and the <strong>critical value</strong>.</p>
<ul>
<li>For df <span class="math inline">= 25</span> and 95%: <span class="math inline">c = 2.06</span>. For df <span class="math inline">&gt; 50</span>, <span class="math inline">\;\hat\beta_j \pm 2\,\text{se}(\hat\beta_j)</span> is a good approximation.</li>
</ul>
<div class="fragment">
<div class="numq" data-id="w5-ci" data-answer="0.00074" data-tol="0.00005">
<p><strong>The 95% CI for <span class="math inline">\beta_{exper}</span> is <span class="math inline">0.00412 \pm 1.965 \times 0.00172</span>. What is its lower bound?</strong> (answer with 5 decimals)</p>
<div class="explain">
<p><span class="math inline">0.00412 - 1.965\times 0.00172 = 0.00412 - 0.00338 = 0.00074</span>, so the CI is <span class="math inline">[0.00074,\; 0.00750]</span>. It excludes 0, which matches the two-sided test: <span class="math inline">p = 0.017 &lt; 0.05</span>.</p>
</div>
</div>
</div>
</section>
<section id="interactive-what-does-95-confidence-mean" class="slide level2 smaller">
<h2>Interactive: what does “95% confidence” mean?</h2>
<div class="widget" data-widget="ci-coverage">

</div>
</section>
<section id="confidence-intervals-and-two-sided-tests" class="slide level2 smaller">
<h2>Confidence intervals and two-sided tests</h2>
<p><span class="math inline">H_0: \beta_j = a_j</span> is <strong>rejected</strong> at level <span class="math inline">\alpha</span> against <span class="math inline">H_1: \beta_j \neq a_j</span> <strong>if and only if</strong> <span class="math inline">a_j</span> lies <strong>outside</strong> the <span class="math inline">100(1-\alpha)\%</span> confidence interval.</p>
<div class="widget" data-widget="ci-duality">

</div>
</section>
<section id="example-a-hedonic-price-model" class="slide level2 smaller">
<h2>Example: a hedonic price model</h2>
<p>A <strong>hedonic</strong> model relates a price to the characteristics of the good (size, rooms, location, …).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"hprice1"</span>)</span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>hed <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(sqrft) <span class="sc">+</span> bdrms, <span class="at">data =</span> hprice1)</span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="fu">coef</span>(hed), <span class="fu">confint</span>(hed)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                     2.5 % 97.5 %
#&gt; (Intercept) -0.623 -2.010  0.764
#&gt; log(sqrft)   0.808  0.612  1.004
#&gt; bdrms        0.038 -0.022  0.098</code></pre>
</div>
</div>
<ul>
<li><strong>Elasticity</strong> of price with respect to size: 0.81, 95% CI [0.61, 1.00]. It excludes 0 (significant), but it <strong>includes 1</strong>: we cannot reject a unit elasticity.</li>
<li>One more <strong>bedroom</strong>, holding size fixed: about +3.8%, but the CI [−2.2%, 9.8%] contains 0.</li>
</ul>
</section>
<section id="reading-a-regression-output" class="slide level2 smaller">
<h2>Reading a regression output</h2>
<p>Click any number to see what it means and how it is computed.</p>
<div class="widget" data-widget="reg-reader">

</div>
</section>
<section id="check-your-understanding" class="slide level2 smaller">
<h2>Check your understanding</h2>
<div class="quiz" data-id="w5-ci-int" data-answer="c">
<p><strong>A 95% CI for <span class="math inline">\beta_1</span> is [0.61, 1.00]. Which statement is correct?</strong></p>
<p><span data-opt="a">A) There is a 95% probability that <span class="math inline">\beta_1</span> is between 0.61 and 1.00</span></p>
<p><span data-opt="b">B) 95% of the houses have an elasticity between 0.61 and 1.00</span></p>
<p><span data-opt="c">C) The procedure that produced this interval captures <span class="math inline">\beta_1</span> in 95% of repeated samples</span></p>
<div class="explain">
<p><span class="math inline">\beta_1</span> is a fixed number: it is either in [0.61, 1.00] or not. The 95% refers to the <strong>method</strong>, as the coverage simulation showed.</p>
</div>
</div>
</section>
<section id="reporting-regression-results" class="slide level2 smaller">
<h2>Reporting regression results</h2>
<ul>
<li>Always report the <strong>estimated coefficients</strong> and interpret the key ones, taking <strong>functional form</strong> and <strong>units</strong> into account.</li>
<li>Report <strong>standard errors</strong> (in parentheses) rather than only <span class="math inline">t</span> statistics: readers can then test other values and build CIs.</li>
<li>Always report <span class="math inline">R^2</span> and <span class="math inline">n</span>. Consider also the SSR and <span class="math inline">\hat\sigma</span>.</li>
</ul>
<p><span class="math display">
\begin{aligned} \widehat{\log(wage)} &amp;=  \underset{\small (0.104)}{0.284} + \underset{\small (0.00733)}{0.0920}\,educ + \underset{\small (0.00172)}{0.00412}\,exper + \underset{\small (0.00309)}{0.0221}\,tenure \\ &amp; n = 526,\quad R^2 = 0.316 \end{aligned}
</span></p>
</section>
<section id="r-toolkit-for-this-topic" class="slide level2 smaller">
<h2>R toolkit for this topic</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ <span class="sc">+</span> exper <span class="sc">+</span> tenure, <span class="at">data =</span> wage1)</span>
<span id="cb12-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res)                       <span class="co"># t values and two-sided p-values for H0: beta = 0</span></span>
<span id="cb12-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">522</span>)                <span class="co"># two-sided 5% critical value</span></span>
<span id="cb12-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>,  <span class="at">df =</span> <span class="dv">522</span>)                <span class="co"># one-sided 5% critical value</span></span>
<span id="cb12-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a aria-hidden="true" tabindex="-1"></a><span class="co"># H0: beta_exper = 0 vs H1: beta_exper &gt; 0 (one-sided p-value)</span></span>
<span id="cb12-8"><a aria-hidden="true" tabindex="-1"></a>tstat <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(res))[<span class="st">"exper"</span>, <span class="st">"t value"</span>]</span>
<span id="cb12-9"><a aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(tstat, <span class="at">df =</span> <span class="dv">522</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-10"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a aria-hidden="true" tabindex="-1"></a><span class="co"># H0: beta = a: compute t yourself</span></span>
<span id="cb12-12"><a aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(res)[<span class="st">"educ"</span>]; se <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(res))[<span class="st">"educ"</span>, <span class="st">"Std. Error"</span>]</span>
<span id="cb12-13"><a aria-hidden="true" tabindex="-1"></a>(b <span class="sc">-</span> <span class="fl">0.10</span>) <span class="sc">/</span> se</span>
<span id="cb12-14"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(res, <span class="at">level =</span> <span class="fl">0.95</span>)          <span class="co"># confidence intervals</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key takeaways</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ol type="1">
<li>Under the CLM assumptions (MLR.1–6), <span class="math inline">(\hat\beta_j - \beta_j)/\text{se}(\hat\beta_j) \sim t_{n-k-1}</span>.</li>
<li><span class="math inline">t = (\hat\beta_j - a_j)/\text{se}(\hat\beta_j)</span>: the distance from <span class="math inline">a_j</span> in <strong>standard errors</strong>.</li>
<li>The <strong>alternative</strong> decides the rejection region: right, left or two-sided.</li>
<li><strong>p-value</strong>: the smallest <span class="math inline">\alpha</span> at which <span class="math inline">H_0</span> is rejected. It is not <span class="math inline">P(H_0 \text{ true})</span>.</li>
<li><strong>CI</strong>: <span class="math inline">\hat\beta_j \pm c\cdot\text{se}(\hat\beta_j)</span>. It contains exactly the values not rejected by a two-sided test.</li>
<li>Statistical significance ≠ economic significance.</li>
</ol>
</div><div class="column" style="width:40%;">
<div class="card">
<p><span class="ct">Next topic</span></p>
<p><strong>Multiple regression III</strong>: testing several restrictions at once (the <span class="math inline">F</span> test), the LM test and large-sample properties of OLS.</p>
<p><span class="tag">Wooldridge ch.&nbsp;4.4–4.5, 5</span> <span class="tag">Heiss ch.&nbsp;4–5</span></p>
</div>
<div class="score-box">

</div>
</div></div>
<script src="assets/deck05.js"></script>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Econometrics I · Yıldız Technical University</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"numbers":true},
'chalkboard': {"buttons":true,"theme":"whiteboard","boardmarkerWidth":3},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 760,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>