<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan">
  <title>Econometrics I – Misspecification and Data Problems</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-70fcdf68ba588c6f83f9e4af10fa12ef.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- shared interactive layer for all Econometrics I decks -->
  <script src="assets/wooldridge-data.js"></script>
  <script src="assets/hmda-data.js"></script>
  <script src="assets/econ-core.js"></script>
  <script src="assets/econ-ui.js"></script>
  <script src="assets/widgets-shared.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Misspecification and Data Problems</h1>
  <p class="subtitle">Topic 12 · Functional form, proxy variables, measurement error and outliers</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.&nbsp;Hüseyin Taştan 
</div>
        <p class="quarto-title-affiliation">
            Yıldız Technical University · Department of Economics
          </p>
    </div>
</div>

  <p class="date">Fall 2026</p>
</section>
<section id="todays-roadmap" class="slide level2">
<h2>Today’s roadmap</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="objectives">
<p><strong>By the end of this lecture you should be able to</strong></p>
<ul>
<li>detect <strong>functional form misspecification</strong> with the <strong>RESET</strong> test</li>
<li>use <strong>proxy variables</strong> to reduce omitted variable bias</li>
<li>explain the consequences of <strong>measurement error</strong> in <span class="math inline">y</span> and in <span class="math inline">x</span></li>
<li>recognize problems caused by <strong>missing data</strong>, <strong>nonrandom samples</strong> and <strong>outliers</strong></li>
</ul>
</div>
</div><div class="column" style="width:45%;">
<div class="card">
<p><span class="ct">Reading</span></p>
<p><span class="tag weektag">Fall 2026 · Week 13</span></p>
<p><span class="tag">Wooldridge ch.&nbsp;9</span> <span class="tag">Heiss ch.&nbsp;9</span></p>
</div>
<div class="card">
<p><span class="ct">Lab</span></p>
<p>R applications and solutions to selected problems. See <em>Lab 13</em> on the course page.</p>
</div>
<div class="card">
<p><span class="ct">Previously</span></p>
<p>Heteroskedasticity broke <strong>MLR.5</strong> but left the estimates unbiased. Today we attack <strong>MLR.4</strong>.</p>
</div>
</div></div>
</section>
<section id="warm-up-which-problem-is-the-most-serious" class="slide level2 smaller">
<h2>Warm-up: which problem is the most serious?</h2>
<div class="quiz" data-id="w12-warmup" data-answer="c">
<p><strong>Which does the most damage to OLS: (i) heteroskedasticity, (ii) omitting a relevant variable or using the wrong functional form, or (iii) measurement error in an explanatory variable?</strong></p>
<p><span data-opt="a">A) (i) is the worst: heteroskedasticity makes OLS biased</span></p>
<p><span data-opt="b">B) (i), (ii) and (iii) are equally bad: each one violates a Gauss–Markov assumption</span></p>
<p><span data-opt="c">C) (ii) and (iii) are worse: they violate MLR.4 and make OLS <strong>biased and inconsistent</strong>, while (i) only distorts the standard errors</span></p>
<div class="explain">
<p>Heteroskedasticity affects only inference, and robust standard errors repair it. Anything that puts something correlated with <span class="math inline">x</span> into the error term, such as an <strong>omitted variable</strong>, a <strong>wrong functional form</strong> or <strong>measurement error in <span class="math inline">x</span></strong>, violates MLR.4 and no amount of data can fix it.</p>
</div>
</div>
</section>
<section>
<section id="functional-form" class="title-slide slide level1 section-slide center">
<h1>Functional form</h1>
<p>When the model is wrong in shape rather than in variables: detecting it with <strong>RESET</strong>.</p>
</section>
<section id="what-counts-as-misspecification" class="slide level2 smaller">
<h2>What counts as misspecification?</h2>
<p>A model is <strong>misspecified in functional form</strong> when it does not capture the relationship between <span class="math inline">y</span> and the <strong>observed</strong> regressors. Examples:</p>
<ul>
<li>fitting a level-level model when a <strong>log</strong> model is correct,</li>
<li>leaving out a <strong>quadratic</strong> term that belongs in the model,</li>
<li>leaving out an <strong>interaction</strong> such as <span class="math inline">female\cdot educ</span>.</li>
</ul>
<div class="fragment">
<p>This is a special kind of <strong>omitted variable</strong> problem: the omitted variable is a <strong>function of the included regressors</strong>, so it is correlated with them and MLR.4 fails.</p>
<div title="Simple remedies first">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Simple remedies first</strong></p>
</div>
<div class="callout-content">
<p>Use <span class="math inline">F</span> tests for joint significance of squares and interactions, and try <strong>logs</strong> for strictly positive variables. Both usually solve the problem.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="ramseys-reset-test-the-idea" class="slide level2 smaller">
<h2>Ramsey’s RESET test: the idea</h2>
<p>If the model is correctly specified, then <strong>no nonlinear function of the regressors</strong> should help explain <span class="math inline">y</span> once the linear terms are in.</p>
<p>We could add every square and cross product, but that costs many degrees of freedom. RESET uses a shortcut. The <strong>fitted value</strong></p>
<p><span class="math display">
\hat y_i = \hat\beta_0 + \hat\beta_1 x_{i1} + \dots + \hat\beta_k x_{ik}
</span></p>
<p>is a <strong>single index</strong> that combines all the regressors. Therefore</p>
<p><span class="math display">
\hat y_i^2 = \big(\hat\beta_0 + \hat\beta_1x_{i1} + \dots\big)^2 = \dots + \hat\beta_1^2x_{i1}^2 + 2\hat\beta_1\hat\beta_2x_{i1}x_{i2} + \dots
</span></p>
<p>already contains <strong>all the squares and cross products</strong> of the <span class="math inline">x_j</span>, in one variable. Adding <span class="math inline">\hat y^2</span> and <span class="math inline">\hat y^3</span> therefore tests for neglected nonlinearity using only <strong>2</strong> degrees of freedom.</p>
</section>
<section id="reset-step-by-step" class="slide level2 smaller">
<h2>RESET step by step</h2>
<div class="card">
<p><span class="ct">Step 1 — estimate the original model and save the fitted values</span></p>
<p><span class="math display">\hat y_i = \hat\beta_0 + \hat\beta_1x_{i1} + \dots + \hat\beta_kx_{ik}, \qquad \text{SSR}_r = \textstyle\sum_i \hat u_i^2</span></p>
</div>
<div class="card">
<p><span class="ct">Step 2 — re-estimate with <span class="math inline">\hat y^2</span> and <span class="math inline">\hat y^3</span> added as two new regressors</span></p>
<p><span class="math display">y = \beta_0 + \beta_1x_1 + \dots + \beta_kx_k + \textcolor{#d9622b}{\gamma_1\hat y^2} + \textcolor{#c0392b}{\gamma_2\hat y^3} + error, \qquad \text{SSR}_{ur}</span></p>
</div>
<div class="card">
<p><span class="ct">Step 3 — test the two added terms jointly with an <span class="math inline">F</span> test</span></p>
<p>The original model is the <strong>restricted</strong> model: it is what we get by setting <span class="math inline">\textcolor{#d9622b}{\gamma_1} = \textcolor{#c0392b}{\gamma_2} = 0</span>.</p>
</div>
</section>
<section id="reset-hypotheses-and-the-test-statistic" class="slide level2 smaller">
<h2>RESET: hypotheses and the test statistic</h2>
<p><span class="math display">
H_0: \textcolor{#d9622b}{\gamma_1} = \textcolor{#c0392b}{\gamma_2} = 0 \qquad\text{(the functional form is correct)}
</span></p>
<p><span class="math display">
H_1: \textcolor{#d9622b}{\gamma_1} \neq 0 \;\text{ or }\; \textcolor{#c0392b}{\gamma_2} \neq 0 \qquad\text{(neglected nonlinearity: the model is misspecified)}
</span></p>
<div class="fragment">
<p>With <span class="math inline">q = 2</span> restrictions and <span class="math inline">k+2</span> regressors in the unrestricted model:</p>
<p><span class="math display">
F = \frac{(\text{SSR}_r - \text{SSR}_{ur})/2}{\text{SSR}_{ur}/(n-k-3)} \;=\; \frac{(R^2_{ur} - R^2_{r})/2}{(1-R^2_{ur})/(n-k-3)} \;\stackrel{H_0}{\sim}\; F_{2,\,n-k-3}
</span></p>
<p>A <strong>large</strong> <span class="math inline">F</span> (small p-value) is evidence <strong>against</strong> the functional form. Note <span class="math inline">H_1</span> does not say <em>which</em> form is right.</p>
</div>
</section>
<section id="interactive-reset-on-house-prices" class="slide level2 smaller">
<h2>Interactive: RESET on house prices</h2>
<div class="widget" data-widget="reset-test">

</div>
<aside class="notes">
<p>Walk through the three steps with the segmented control. Step 1: y against yhat, the 45-degree line shows what the model predicts. Step 2: the residuals still curve with yhat, so yhat^2 and yhat^3 pick something up. Step 3: the F statistic falls in the rejection region for the level-level model but not for the log-log model.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reset-in-r" class="slide level2 smaller">
<h2>RESET in R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a>h1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> lotsize <span class="sc">+</span> sqrft <span class="sc">+</span> bdrms, <span class="at">data =</span> hprice1)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(h1, <span class="at">power =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">type =</span> <span class="st">"fitted"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;  RESET test
#&gt; 
#&gt; data:  h1
#&gt; RESET = 4.6682, df1 = 2, df2 = 82, p-value = 0.01202</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>h2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lprice <span class="sc">~</span> llotsize <span class="sc">+</span> lsqrft <span class="sc">+</span> bdrms, <span class="at">data =</span> hprice1)</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(h2, <span class="at">power =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">type =</span> <span class="st">"fitted"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;  RESET test
#&gt; 
#&gt; data:  h2
#&gt; RESET = 2.565, df1 = 2, df2 = 82, p-value = 0.08308</code></pre>
</div>
</div>
<p>The level-level model is rejected at 5% (<span class="math inline">p = 0.012</span>); the log-log model is not (<span class="math inline">p = 0.083</span>). We prefer the <strong>log-log</strong> specification.</p>
</section>
<section id="what-reset-can-and-cannot-do" class="slide level2 smaller">
<h2>What RESET can and cannot do</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Can</strong></p>
<ul>
<li>detect neglected <strong>nonlinearities</strong> in the included regressors</li>
<li>work with any <span class="math inline">k</span>, using only 2 degrees of freedom</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Cannot</strong></p>
<ul>
<li>tell you <strong>how</strong> to fix the model</li>
<li>detect an omitted variable that enters <strong>linearly</strong></li>
<li>substitute for a test of heteroskedasticity</li>
</ul>
</div></div>
<div class="fragment">
<p><strong>Non-nested models</strong>, e.g.&nbsp;<span class="math inline">y = \beta_0+\beta_1x_1+\beta_2x_2+u</span> vs.&nbsp;<span class="math inline">y = \beta_0+\beta_1\log x_1+\beta_2\log x_2+u</span>, cannot be compared with an <span class="math inline">F</span> test. Options: the <strong>Mizon–Richard</strong> approach (nest both in a larger model) or the <strong>Davidson–MacKinnon</strong> test (add the fitted values of one model to the other). Both can reject both models, or neither.</p>
</div>
</section></section>
<section>
<section id="proxy-variables" class="title-slide slide level1 section-slide center">
<h1>Proxy variables</h1>
<p>Putting an imperfect stand-in for an unobserved factor into the regression.</p>
</section>
<section id="using-a-proxy-for-something-unobserved" class="slide level2 smaller">
<h2>Using a proxy for something unobserved</h2>
<p><span class="math display">
\log(wage) = \beta_0 + \beta_1 educ + \beta_2 exper + \beta_3\,\underbrace{abil}_{\text{unobserved}} + u
</span></p>
<p>Omitting ability biases <span class="math inline">\hat\beta_1</span> upward. A <strong>proxy</strong> $abil^* $ (e.g.&nbsp;an IQ score) can help if</p>
<ol type="1">
<li>it is <strong>correlated</strong> with ability: <span class="math inline">\;abil = \delta_0 + \delta_3\,abil^* + v_3</span> with <span class="math inline">\delta_3 \neq 0</span>,</li>
<li>once the proxy is included, the unobservable is <strong>no longer correlated</strong> with the regressors: <span class="math display">E(abil \mid educ, exper, abil^*) = E(abil\mid abil^*)</span></li>
</ol>
<p>Then the <strong>plug-in solution</strong> (just add the proxy to the regression) gives consistent estimates of <span class="math inline">\beta_1</span> and <span class="math inline">\beta_2</span>.</p>
</section>
<section id="example-iq-as-a-proxy-for-ability-wage2" class="slide level2 smaller">
<h2>Example: IQ as a proxy for ability (<code>wage2</code>)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> educ <span class="sc">+</span> exper <span class="sc">+</span> tenure <span class="sc">+</span> married <span class="sc">+</span> south <span class="sc">+</span> urban <span class="sc">+</span> black, <span class="at">data =</span> wage2)</span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">update</span>(p0, . <span class="sc">~</span> . <span class="sc">+</span> IQ)</span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">without_IQ =</span> <span class="fu">coef</span>(p0), <span class="at">with_IQ =</span> <span class="fu">coef</span>(p1)[<span class="fu">names</span>(<span class="fu">coef</span>(p0))]), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;             without_IQ with_IQ
#&gt; (Intercept)     5.3955  5.1764
#&gt; educ            0.0654  0.0544
#&gt; exper           0.0140  0.0141
#&gt; tenure          0.0117  0.0114
#&gt; married         0.1994  0.1998
#&gt; south          -0.0909 -0.0802
#&gt; urban           0.1839  0.1819
#&gt; black          -0.1883 -0.1431</code></pre>
</div>
</div>
<ul>
<li>The return to education falls from <strong>6.5%</strong> to <strong>5.4%</strong> once IQ is controlled for: part of what looked like a return to schooling was <strong>ability</strong>.</li>
<li>The coefficient on <code>black</code> also shrinks in absolute value (from <span class="math inline">-0.188</span> to <span class="math inline">-0.143</span>).</li>
<li>IQ itself: <span class="math inline">\hat\beta_{IQ} = 0.0036</span> (<span class="math inline">t = 3.6</span>), i.e.&nbsp;10 more IQ points are associated with 3.6% higher wages.</li>
</ul>
</section>
<section id="a-lagged-dependent-variable-as-a-proxy" class="slide level2 smaller">
<h2>A lagged dependent variable as a proxy</h2>
<p>When we cannot even <strong>name</strong> the omitted factor, a <strong>lagged value of <span class="math inline">y</span></strong> can stand in for it. City crime rates in 1987 (<code>crime2</code>, 46 cities):</p>
<p><span class="math display">
\log(crmrte_{87}) = \beta_0 + \beta_1 unem_{87} + \beta_2\log(lawexpc_{87}) + \beta_3\log(crmrte_{82}) + u
</span></p>
<p>Cities differ in ways we never observe: poverty, the age structure, policing culture. All of these already showed up in the <strong>1982 crime rate</strong>, so <span class="math inline">\log(crmrte_{82})</span> proxies for them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-hidden="true" tabindex="-1"></a>c1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lcrmrte <span class="sc">~</span> unem <span class="sc">+</span> llawexpc, <span class="at">data =</span> crime2, <span class="at">subset =</span> year <span class="sc">==</span> <span class="dv">87</span>)</span>
<span id="cb7-2"><a aria-hidden="true" tabindex="-1"></a>c2 <span class="ot">&lt;-</span> <span class="fu">update</span>(c1, . <span class="sc">~</span> . <span class="sc">+</span> lcrmrt_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="the-two-estimated-equations" class="slide level2 smaller">
<h2>The two estimated equations</h2>
<p><span class="ct">Without the proxy</span></p>
<p><span class="math display">
\begin{aligned} \widehat{\log(crmrte_{87})} &amp;=  \underset{\small (1.25)}{3.34} - \underset{\small (0.0323)}{0.0290}\,unem + \underset{\small (0.173)}{0.203}\,\log(lawexpc) \end{aligned}
</span></p>
<p><span class="ct">With the lagged crime rate as a proxy</span></p>
<p><span class="math display">
\begin{aligned} \widehat{\log(crmrte_{87})} &amp;=  \underset{\small (0.821)}{0.0765} + \underset{\small (0.0195)}{0.00862}\,unem - \underset{\small (0.109)}{0.140}\,\log(lawexpc) \\ &amp; + \underset{\small (0.132)}{1.19}\,\log(crmrte82) \end{aligned}
</span></p>
<div class="fragment">
<ul>
<li>Without the lag, unemployment appears to <strong>lower</strong> crime, which is hard to believe.</li>
<li>With the proxy the sign flips to <strong>positive</strong> (still insignificant), and <span class="math inline">R^2</span> rises from <strong>0.06 to 0.68</strong>.</li>
<li>The lag is here only to <strong>absorb unobservables</strong>, not as a causal effect of past crime.</li>
</ul>
</div>
</section></section>
<section>
<section id="data-problems" class="title-slide slide level1 section-slide center">
<h1>Data problems</h1>

</section>
<section id="data-problems-what-can-go-wrong" class="slide level2 smaller">
<h2>Data problems: what can go wrong</h2>
<p>So far the model was the problem. Now the <strong>data</strong> are:</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">1. Measurement error</span></p>
<p>We observe an imperfect version of a variable. Consequences differ completely for <span class="math inline">y</span> and for <span class="math inline">x</span> — the next three slides.</p>
</div>
<div class="card">
<p><span class="ct">2. Missing data</span></p>
<p>Observations with a missing value are dropped. Harmless or not, depending on <strong>why</strong> they are missing.</p>
</div>
</div><div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">3. Nonrandom samples</span></p>
<p>The sample was selected on the regressors (harmless) or on the dependent variable (<strong>biased</strong>).</p>
</div>
<div class="card">
<p><span class="ct">4. Outliers and influential observations</span></p>
<p>A single observation moves the estimates because OLS minimizes <strong>squared</strong> residuals.</p>
</div>
</div></div>
</section>
<section id="measurement-error-in-the-dependent-variable" class="slide level2 smaller">
<h2>Measurement error in the dependent variable</h2>
<p>Let <span class="math inline">y</span> be the true variable and <span class="math inline">y^*</span> the one we <strong>observe</strong> (reported savings, reported hours). The measurement error is <span class="math inline">e_0 = y^* - y</span>, and the model we care about is <span class="math inline">y = \beta_0 + \beta_1x_1 + \dots + \beta_kx_k + u</span>. Substituting <span class="math inline">y = y^* - e_0</span>:</p>
<p><span class="math display">
y^* = \beta_0 + \beta_1x_1 + \dots + \beta_kx_k + \underbrace{(u + e_0)}_{\text{new error}}
</span></p>
<div class="fragment">
<ul>
<li>If <span class="math inline">E(e_0) = 0</span> and <span class="math inline">e_0</span> is <strong>uncorrelated with the regressors</strong>, all Gauss–Markov assumptions still hold: OLS on the observed <span class="math inline">y^*</span> is <strong>unbiased and consistent</strong>.</li>
<li>The only cost is precision: <span class="math inline">\text{Var}(u + e_0) = \sigma_u^2 + \sigma_{e_0}^2 &gt; \sigma_u^2</span>, so <strong>standard errors are larger</strong>.</li>
<li>If instead <span class="math inline">e_0</span> is correlated with an <span class="math inline">x_j</span> (e.g.&nbsp;the highly educated under-report income), MLR.4 fails and OLS <strong>is</strong> biased.</li>
</ul>
</div>
</section>
<section id="measurement-error-in-an-explanatory-variable" class="slide level2 smaller">
<h2>Measurement error in an explanatory variable</h2>
<p>Now <span class="math inline">x_1</span> is measured with error: we observe <span class="math inline">x_1^* = x_1 + e_1</span> and run the regression with <span class="math inline">x_1^*</span>. Everything depends on <strong>what <span class="math inline">e_1</span> is uncorrelated with</strong>.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">Case 1: <span class="math inline">\text{Cov}(x_1^*, e_1) = 0</span></span></p>
<p>The error is unrelated to the <strong>measure</strong> we actually use. Then <span class="math inline">x_1^*</span> is uncorrelated with the composite error and OLS is <strong>consistent</strong>; only <span class="math inline">\sigma^2</span> and the standard errors grow.</p>
</div>
</div><div class="column" style="width:50%;">
<div class="card">
<p><span class="ct">Case 2: <span class="math inline">\text{Cov}(x_1, e_1) = 0</span> (CEV)</span></p>
<p>The <strong>classical errors-in-variables</strong> assumption: the error is unrelated to the <strong>true</strong> value. This is the usual case, and now OLS is <strong>inconsistent</strong>.</p>
</div>
</div></div>
<div class="fragment">
<p>The two cases cannot both hold (unless <span class="math inline">\sigma_{e_1}^2 = 0</span>): under CEV, <span class="math inline">\text{Cov}(x_1^*, e_1) = \text{Cov}(x_1 + e_1, e_1) = \sigma_{e_1}^2 \neq 0</span>.</p>
</div>
</section>
<section id="where-attenuation-bias-comes-from" class="slide level2 smaller">
<h2>Where attenuation bias comes from</h2>
<p>Write the true model in terms of the variable we <strong>observe</strong>, <span class="math inline">x_1 = x_1^* - e_1</span>:</p>
<p><span class="math display">
y = \beta_0 + \beta_1x_1 + u = \beta_0 + \beta_1x_1^* + \underbrace{(u - \beta_1 e_1)}_{\text{new error}}
</span></p>
<p>The regressor and the error now move together, and under CEV the covariance is</p>
<p><span class="math display">
\text{Cov}(x_1^*,\, u - \beta_1e_1) = -\beta_1\text{Cov}(x_1 + e_1,\, e_1) = -\beta_1\sigma_{e_1}^2
</span></p>
<div class="fragment">
<p><span class="math display">
\text{plim}\,\hat\beta_1 = \beta_1 + \frac{-\beta_1\sigma_{e_1}^2}{\sigma_{x_1}^2 + \sigma_{e_1}^2} = \beta_1\,\underbrace{\frac{\sigma_{x_1}^2}{\sigma_{x_1}^2+\sigma_{e_1}^2}}_{\text{between 0 and 1}}
</span></p>
<p>The multiplying factor is always <strong>less than one</strong>: the estimate shrinks <strong>toward zero</strong>. This is <strong>attenuation bias</strong>, and a larger sample does not remove it.</p>
</div>
</section>
<section id="interactive-attenuation-bias" class="slide level2 smaller">
<h2>Interactive: attenuation bias</h2>
<div class="widget" data-widget="meas-error">

</div>
<aside class="notes">
<p>With sigma_e = 0 the OLS slope is 1. Increase it: the cloud spreads horizontally and the fitted line flattens, exactly following the plim formula. At sigma_e = 1 the estimate is halved. Ask students what this implies for survey data on income or hours worked.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="missing-data-and-nonrandom-samples" class="slide level2 smaller">
<h2>Missing data and nonrandom samples</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p><strong>Missing data</strong></p>
<ul>
<li>R drops incomplete observations, so <span class="math inline">n</span> falls and the estimates are less precise.</li>
<li>If data are <strong>missing at random</strong>, no bias.</li>
<li>If they are missing <strong>systematically</strong> (e.g.&nbsp;low-education respondents skip the education question), OLS can be biased.</li>
</ul>
</div><div class="column" style="width:48%;">
<p><strong>Nonrandom sampling</strong></p>
<ul>
<li><strong>Exogenous</strong> selection, based on the <strong>regressors</strong> (e.g.&nbsp;only people over 35), is harmless.</li>
<li><strong>Endogenous</strong> selection, based on the <strong>dependent variable</strong> (e.g.&nbsp;only households with wealth below $250,000), violates MLR.2 and <strong>biases</strong> OLS.</li>
</ul>
</div></div>
<div title="Example">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>If IQ scores are easier to obtain for people with high IQ, the sample over-represents them and the estimates are biased.</p>
</div>
</div>
</div>
</div>
</section>
<section id="outliers-and-influential-observations" class="slide level2 smaller">
<h2>Outliers and influential observations</h2>
<p>An observation is <strong>influential</strong> if dropping it changes the estimates by a lot. OLS is sensitive because it minimizes <strong>squared</strong> residuals.</p>
<div class="widget" data-widget="outliers">

</div>
<aside class="notes">
<p>Click the red dot (sales of $39.7 billion, about twice the next largest firm): the coefficient on sales goes from 0.00005 (t = 1.2) to 0.00019 (t = 2.2). Then switch to the log-log model and drop the same firm: the elasticity hardly moves, 1.084 vs 1.088. Logs shrink the range of the data, so they are much less sensitive.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-to-do-about-outliers" class="slide level2 smaller">
<h2>What to do about outliers</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a>r_all  <span class="ot">&lt;-</span> <span class="fu">lm</span>(rdintens <span class="sc">~</span> sales <span class="sc">+</span> profmarg, <span class="at">data =</span> rdchem)</span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a>r_drop <span class="ot">&lt;-</span> <span class="fu">lm</span>(rdintens <span class="sc">~</span> sales <span class="sc">+</span> profmarg, <span class="at">data =</span> rdchem[<span class="sc">-</span><span class="fu">which.max</span>(rdchem<span class="sc">$</span>sales), ])</span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">all =</span> <span class="fu">coef</span>(r_all), <span class="at">without_largest =</span> <span class="fu">coef</span>(r_drop)), <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                 all without_largest
#&gt; (Intercept) 2.62526         2.29685
#&gt; sales       0.00005         0.00019
#&gt; profmarg    0.04462         0.04784</code></pre>
</div>
</div>
<div class="columns">
<div class="column" style="width:55%;">
<ol type="1">
<li>First check whether it is a <strong>data entry error</strong> (a misplaced decimal point, an extra zero).</li>
<li>If it is a genuine feature of the distribution, <strong>do not delete it silently</strong>.</li>
<li>Report the results <strong>with and without</strong> the observation.</li>
<li>Consider a <strong>log transformation</strong>, which narrows the range and often removes the problem.</li>
</ol>
</div><div class="column" style="width:45%;">
<div title="Outliers can be informative">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Outliers can be informative</strong></p>
</div>
<div class="callout-content">
<p>An extreme value also adds <strong>variation in <span class="math inline">x</span></strong>, which lowers the standard errors. The goal is transparency, not removal.</p>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="check-your-understanding" class="slide level2 smaller">
<h2>Check your understanding</h2>
<div class="quiz" data-id="w12-check" data-answer="b">
<p><strong>A survey measures household income with error. Income is the explanatory variable. What happens?</strong></p>
<p><span data-opt="a">A) OLS stays consistent, only the standard errors grow</span></p>
<p><span data-opt="b">B) The estimated coefficient on income is biased toward zero (attenuation), and a larger sample does not help</span></p>
<p><span data-opt="c">C) The intercept is biased, but the slope is fine</span></p>
<div class="explain">
<p>Under the classical errors-in-variables assumption the mismeasured regressor is correlated with the composite error, so OLS is <strong>inconsistent</strong>. Answer (A) describes measurement error in the <strong>dependent</strong> variable.</p>
</div>
</div>
</section>
<section id="r-toolkit-for-this-topic" class="slide level2 smaller">
<h2>R toolkit for this topic</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(m, <span class="at">power =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">type =</span> <span class="st">"fitted"</span>)      <span class="co"># RESET</span></span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># proxy variable: just add it</span></span>
<span id="cb10-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">update</span>(m, . <span class="sc">~</span> . <span class="sc">+</span> IQ)</span>
<span id="cb10-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a aria-hidden="true" tabindex="-1"></a><span class="co"># influence diagnostics</span></span>
<span id="cb10-8"><a aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m, <span class="at">which =</span> <span class="dv">4</span>)            <span class="co"># Cook's distance</span></span>
<span id="cb10-9"><a aria-hidden="true" tabindex="-1"></a><span class="fu">influence.measures</span>(m)         <span class="co"># dfbeta, dffits, hat values</span></span>
<span id="cb10-10"><a aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">update</span>(m, <span class="at">data =</span> df[<span class="sc">-</span><span class="fu">which.max</span>(df<span class="sc">$</span>sales), ])   <span class="co"># refit without one observation</span></span>
<span id="cb10-11"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)<span class="sc">$</span>df[<span class="dv">2</span>]              <span class="co"># degrees of freedom: how many observations were kept</span></span>
<span id="cb10-13"><a aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(df))            <span class="co"># where are the missing values?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key takeaways</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ol type="1">
<li>Wrong <strong>functional form</strong> is an omitted variable problem: use logs, quadratics, interactions and the <strong>RESET</strong> test.</li>
<li>A <strong>proxy variable</strong> can cut omitted variable bias: with IQ in the model, the return to education falls from 6.5% to 5.4%.</li>
<li>Measurement error in <strong><span class="math inline">y</span></strong>: harmless on average. In <strong><span class="math inline">x</span></strong>: <strong>attenuation bias</strong> and inconsistency.</li>
<li><strong>Missing data</strong> and <strong>nonrandom samples</strong> are harmless only if unrelated to <span class="math inline">y</span> given the regressors.</li>
<li><strong>Outliers</strong>: investigate, report with and without, and consider logs.</li>
</ol>
</div><div class="column" style="width:40%;">
<div class="card">
<p><span class="ct">Where this course ends</span></p>
<p>The remaining problems (endogeneity, simultaneity) need <strong>instrumental variables</strong> and <strong>2SLS</strong>: Econometrics II.</p>
<p><span class="tag">Wooldridge ch.&nbsp;15</span></p>
</div>
<div class="score-box">

</div>
</div></div>
<script src="assets/deck12.js"></script>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Econometrics I · Yıldız Technical University</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"numbers":true},
'chalkboard': {"buttons":true,"theme":"whiteboard","boardmarkerWidth":3},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 760,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>